local M = {}

function M.setup(config)
  local c = require("rp.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.midnight_violet
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.pale_lavender, bg = normal_bg },
    NormalNC = { fg = c.lavender_gray, bg = normal_bg },
    NormalFloat = { fg = c.pale_lavender, bg = c.dark_violet_gray },
    FloatBorder = { fg = c.medium_violet_gray, bg = c.dark_violet_gray },
    FloatTitle = { fg = c.pale_rose, bg = c.dark_violet_gray, bold = true },
    Cursor = { fg = c.midnight_violet, bg = c.pale_lavender },
    NonText = { fg = c.muted_violet_gray },
    EndOfBuffer = { fg = c.midnight_violet },
    Whitespace = { fg = c.muted_violet_gray },
    SpecialKey = { fg = c.lavender_gray },
    LineNr = { fg = c.muted_violet_gray, bg = normal_bg },
    CursorLineNr = { fg = c.pale_rose, bg = normal_bg, bold = true },
    CursorLine = { bg = c.medium_violet_gray },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.deep_violet_gray },
    SignColumn = { fg = c.lavender_gray, bg = normal_bg },
    CursorLineSign = { bg = c.deep_violet_gray },
    FoldColumn = { fg = c.muted_violet_gray, bg = normal_bg },
    Folded = { fg = c.lavender_gray, bg = c.deep_violet_gray },
    MatchParen = { fg = c.pale_gold, bg = c.muted_indigo_gray, bold = true },
    Visual = { bg = c.muted_indigo_gray },
    VisualNOS = { bg = c.deep_violet_gray },
    Search = { fg = c.midnight_violet, bg = c.pale_rose },
    IncSearch = { fg = c.midnight_violet, bg = c.pale_gold },
    CurSearch = { fg = c.midnight_violet, bg = c.pale_gold, bold = true },
    Substitute = { fg = c.midnight_violet, bg = c.dusty_pink },
    Pmenu = { fg = c.pale_lavender, bg = c.dark_violet_gray },
    PmenuSel = { fg = c.pale_lavender, bg = c.muted_indigo_gray, bold = true },
    PmenuKind = { fg = c.pale_cyan, bg = c.dark_violet_gray },
    PmenuExtra = { fg = c.lavender_gray, bg = c.dark_violet_gray },
    PmenuSbar = { bg = c.dark_violet_gray },
    PmenuThumb = { bg = c.medium_violet_gray },
    StatusLine = { fg = c.muted_violet_gray, bg = normal_bg },
    StatusLineNC = { fg = c.muted_violet_gray, bg = normal_bg },
    TabLine = { fg = c.lavender_gray, bg = c.dark_violet_gray },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.pale_lavender, bg = c.deep_violet_gray, bold = true },
    WinSeparator = { fg = c.muted_violet_gray, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.pale_lavender, bg = c.muted_indigo_gray, bold = true },
    Directory = { fg = c.pale_cyan },
    Title = { fg = c.pale_rose, bold = true },
    Question = { fg = c.pale_cyan },
    MoreMsg = { fg = c.pale_cyan },
    ModeMsg = { fg = c.pale_gold, bold = true },
    WarningMsg = { fg = c.pale_gold },
    ErrorMsg = { fg = c.dusty_pink },
    Error = { fg = c.dusty_pink },
    Todo = { fg = c.midnight_violet, bg = c.pale_gold, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.muted_violet_gray }, comment_style),
    SpecialComment = { fg = c.lavender_gray, italic = true },
    Constant = { fg = c.pale_gold },
    String = { fg = c.pale_gold },
    Character = { fg = c.pale_gold },
    Number = { fg = c.pale_gold },
    Boolean = { fg = c.pale_gold, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.pale_lavender },
    Function = { fg = c.pale_rose },
    Statement = vim.tbl_extend("force", { fg = c.light_violet }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.dark_teal_blue }, keyword_style),
    Operator = { fg = c.lavender_gray },
    Exception = { fg = c.dusty_pink },
    PreProc = { fg = c.dark_teal_blue },
    Type = { fg = c.pale_cyan },
    Special = { fg = c.light_violet },
    Delimiter = { fg = c.lavender_gray },
    Underlined = { fg = c.light_violet, underline = true },
    Ignore = { fg = c.muted_violet_gray },

    DiffAdd = { bg = c.deep_violet_gray },
    DiffChange = { bg = c.muted_indigo_gray },
    DiffDelete = { fg = c.dusty_pink, bg = c.deep_violet_gray },
    DiffText = { bg = c.medium_violet_gray, bold = true },
    Added = { fg = c.pale_cyan },
    Changed = { fg = c.pale_gold },
    Removed = { fg = c.dusty_pink },

    DiagnosticError = { fg = c.dusty_pink },
    DiagnosticWarn = { fg = c.pale_gold },
    DiagnosticInfo = { fg = c.pale_cyan },
    DiagnosticHint = { fg = c.light_violet },
    DiagnosticOk = { fg = c.dark_teal_blue },
    DiagnosticUnderlineError = { sp = c.dusty_pink, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.pale_gold, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.pale_cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.light_violet, undercurl = true },
    LspReferenceText = { bg = c.muted_indigo_gray },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.muted_indigo_gray, underline = true },
    LspSignatureActiveParameter = { fg = c.pale_rose, bold = true },
    LspCodeLens = { fg = c.muted_violet_gray },

    SpellBad = { sp = c.dusty_pink, undercurl = true },
    SpellCap = { sp = c.pale_cyan, undercurl = true },
    SpellRare = { sp = c.light_violet, undercurl = true },
    SpellLocal = { sp = c.pale_gold, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.dark_teal_blue },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.pale_gold, bold = true },
    ["@variable"] = { fg = c.pale_lavender },
    ["@variable.builtin"] = { fg = c.dusty_pink, italic = true },
    ["@variable.parameter"] = { fg = c.light_violet },
    ["@variable.member"] = { fg = c.pale_cyan },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.dusty_pink },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { fg = c.pale_cyan },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.dark_teal_blue },
    ["@keyword.operator"] = { fg = c.dark_teal_blue },
    ["@keyword.return"] = { fg = c.dark_teal_blue },
    ["@keyword.import"] = { fg = c.dark_teal_blue },
    ["@keyword.type"] = { fg = c.dark_teal_blue },
    ["@operator"] = { link = "Operator" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.lavender_gray },
    ["@punctuation.delimiter"] = { fg = c.lavender_gray },
    ["@punctuation.special"] = { fg = c.dark_teal_blue },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.pale_cyan, italic = true },
    ["@module"] = { fg = c.pale_lavender },
    ["@namespace"] = { link = "@module" },
    ["@property"] = { fg = c.pale_cyan },
    ["@attribute"] = { fg = c.light_violet },
    ["@tag"] = { fg = c.pale_rose },
    ["@tag.attribute"] = { fg = c.pale_cyan },
    ["@tag.delimiter"] = { fg = c.lavender_gray },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.light_violet, underline = true },
    ["@markup.raw"] = { link = "String" },

    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.keyword"] = { link = "Keyword" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.readonly"] = { link = "Constant" },
    ["@lsp.mod.defaultLibrary"] = { link = "Special" },

    GitSignsAdd = { fg = c.pale_cyan },
    GitSignsChange = { fg = c.pale_gold },
    GitSignsDelete = { fg = c.dusty_pink },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.muted_indigo_gray, bold = true },
    TelescopeMatching = { fg = c.pale_rose, bold = true },
    BlinkCmpLabelMatch = { fg = c.pale_rose, bold = true },
    CmpItemAbbrMatch = { fg = c.pale_rose, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.pale_cyan, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    Include = "PreProc", Define = "PreProc", Macro = "PreProc", PreCondit = "PreProc",
    StorageClass = "Type", Structure = "Type", Typedef = "Type", Debug = "Special",
    SpecialChar = "Special", Tag = "Special", Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
