local M = {}

function M.setup(config)
  local c = require("rp.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.base
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.text, bg = normal_bg },
    NormalNC = { fg = c.subtle, bg = config.transparent and none or c.nc },
    NormalFloat = { fg = c.text, bg = c.surface },
    FloatBorder = { fg = c.highlight_high, bg = c.surface },
    FloatTitle = { fg = c.rose, bg = c.surface, bold = true },
    Cursor = { fg = c.base, bg = c.text },
    NonText = { fg = c.muted },
    EndOfBuffer = { fg = c.base },
    Whitespace = { fg = c.muted },
    SpecialKey = { fg = c.subtle },
    LineNr = { fg = c.muted, bg = normal_bg },
    CursorLineNr = { fg = c.rose, bg = normal_bg, bold = true },
    CursorLine = { bg = c.highlight_low },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.highlight_low },
    SignColumn = { fg = c.subtle, bg = normal_bg },
    CursorLineSign = { bg = c.highlight_low },
    FoldColumn = { fg = c.muted, bg = normal_bg },
    Folded = { fg = c.subtle, bg = c.highlight_low },
    MatchParen = { fg = c.gold, bg = c.highlight_med, bold = true },
    Visual = { bg = c.highlight_med },
    VisualNOS = { bg = c.highlight_low },
    Search = { fg = c.base, bg = c.rose },
    IncSearch = { fg = c.base, bg = c.gold },
    CurSearch = { fg = c.base, bg = c.gold, bold = true },
    Substitute = { fg = c.base, bg = c.love },
    Pmenu = { fg = c.text, bg = c.surface },
    PmenuSel = { fg = c.text, bg = c.highlight_med, bold = true },
    PmenuKind = { fg = c.foam, bg = c.surface },
    PmenuExtra = { fg = c.subtle, bg = c.surface },
    PmenuSbar = { bg = c.surface },
    PmenuThumb = { bg = c.highlight_high },
    StatusLine = { fg = c.subtle, bg = normal_bg },
    StatusLineNC = { fg = c.muted, bg = normal_bg },
    TabLine = { fg = c.subtle, bg = c.surface },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.text, bg = c.highlight_low, bold = true },
    WinSeparator = { fg = c.muted, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.text, bg = c.highlight_med, bold = true },
    Directory = { fg = c.foam },
    Title = { fg = c.rose, bold = true },
    Question = { fg = c.foam },
    MoreMsg = { fg = c.foam },
    ModeMsg = { fg = c.gold, bold = true },
    WarningMsg = { fg = c.gold },
    ErrorMsg = { fg = c.love },
    Error = { fg = c.love },
    Todo = { fg = c.base, bg = c.gold, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.muted }, comment_style),
    SpecialComment = { fg = c.subtle, italic = true },
    Constant = { fg = c.gold },
    String = { fg = c.gold },
    Character = { fg = c.gold },
    Number = { fg = c.gold },
    Boolean = { fg = c.gold, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.text },
    Function = { fg = c.rose },
    Statement = vim.tbl_extend("force", { fg = c.iris }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.pine }, keyword_style),
    Operator = { fg = c.subtle },
    Exception = { fg = c.love },
    PreProc = { fg = c.pine },
    Type = { fg = c.foam },
    Special = { fg = c.iris },
    Delimiter = { fg = c.subtle },
    Underlined = { fg = c.iris, underline = true },
    Ignore = { fg = c.muted },

    DiffAdd = { bg = c.highlight_low },
    DiffChange = { bg = c.highlight_med },
    DiffDelete = { fg = c.love, bg = c.highlight_low },
    DiffText = { bg = c.highlight_high, bold = true },
    Added = { fg = c.foam },
    Changed = { fg = c.gold },
    Removed = { fg = c.love },

    DiagnosticError = { fg = c.love },
    DiagnosticWarn = { fg = c.gold },
    DiagnosticInfo = { fg = c.foam },
    DiagnosticHint = { fg = c.iris },
    DiagnosticOk = { fg = c.pine },
    DiagnosticUnderlineError = { sp = c.love, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.gold, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.foam, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.iris, undercurl = true },
    LspReferenceText = { bg = c.highlight_med },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.highlight_med, underline = true },
    LspSignatureActiveParameter = { fg = c.rose, bold = true },
    LspCodeLens = { fg = c.muted },

    SpellBad = { sp = c.love, undercurl = true },
    SpellCap = { sp = c.foam, undercurl = true },
    SpellRare = { sp = c.iris, undercurl = true },
    SpellLocal = { sp = c.gold, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.pine },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.gold, bold = true },
    ["@variable"] = { fg = c.text },
    ["@variable.builtin"] = { fg = c.love, italic = true },
    ["@variable.parameter"] = { fg = c.iris },
    ["@variable.member"] = { fg = c.foam },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.love },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { fg = c.foam },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.pine },
    ["@keyword.operator"] = { fg = c.pine },
    ["@keyword.return"] = { fg = c.pine },
    ["@keyword.import"] = { fg = c.pine },
    ["@keyword.type"] = { fg = c.pine },
    ["@operator"] = { link = "Operator" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.subtle },
    ["@punctuation.delimiter"] = { fg = c.subtle },
    ["@punctuation.special"] = { fg = c.pine },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.foam, italic = true },
    ["@module"] = { fg = c.text },
    ["@namespace"] = { link = "@module" },
    ["@property"] = { fg = c.foam },
    ["@attribute"] = { fg = c.iris },
    ["@tag"] = { fg = c.rose },
    ["@tag.attribute"] = { fg = c.foam },
    ["@tag.delimiter"] = { fg = c.subtle },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.iris, underline = true },
    ["@markup.raw"] = { link = "String" },

    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.keyword"] = { link = "Keyword" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.readonly"] = { link = "Constant" },
    ["@lsp.mod.defaultLibrary"] = { link = "Special" },

    GitSignsAdd = { fg = c.foam },
    GitSignsChange = { fg = c.gold },
    GitSignsDelete = { fg = c.love },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.highlight_med, bold = true },
    TelescopeMatching = { fg = c.rose, bold = true },
    BlinkCmpLabelMatch = { fg = c.rose, bold = true },
    CmpItemAbbrMatch = { fg = c.rose, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.foam, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    Include = "PreProc", Define = "PreProc", Macro = "PreProc", PreCondit = "PreProc",
    StorageClass = "Type", Structure = "Type", Typedef = "Type", Debug = "Special",
    SpecialChar = "Special", Tag = "Special", Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
