local M = {}

function M.setup(config)
  local c = require("md.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.charcoal_black
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.light_blue_gray, bg = normal_bg },
    NormalNC = { fg = c.medium_gray, bg = normal_bg },
    NormalFloat = { fg = c.light_blue_gray, bg = c.near_black },
    FloatBorder = { fg = c.charcoal_gray, bg = c.near_black },
    FloatTitle = { fg = c.icy_white, bg = c.near_black, bold = true },
    Cursor = { fg = c.charcoal_black, bg = c.bright_yellow },
    NonText = { fg = c.medium_dark_gray },
    EndOfBuffer = { fg = c.charcoal_black },
    Whitespace = { fg = c.medium_dark_gray },
    SpecialKey = { fg = c.muted_gray },
    LineNr = { fg = c.muted_gray, bg = normal_bg },
    CursorLineNr = { fg = c.vivid_orange, bg = normal_bg, bold = true },
    CursorLine = { bg = c.medium_charcoal },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.medium_charcoal },
    SignColumn = { fg = c.muted_gray, bg = normal_bg },
    CursorLineSign = { bg = c.medium_charcoal },
    FoldColumn = { fg = c.muted_gray, bg = normal_bg },
    Folded = { fg = c.medium_gray, bg = c.medium_charcoal },
    MatchParen = { fg = c.vivid_orange, bold = true },
    Visual = { bg = c.dark_gray },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.charcoal_black, bg = c.vivid_orange },
    IncSearch = { fg = c.charcoal_black, bg = c.warm_yellow },
    CurSearch = { fg = c.charcoal_black, bg = c.warm_yellow, bold = true },
    Substitute = { fg = c.charcoal_black, bg = c.salmon_orange },
    Pmenu = { fg = c.light_blue_gray, bg = c.near_black },
    PmenuSel = { fg = c.icy_white, bg = c.muted_charcoal, bold = true },
    PmenuKind = { fg = c.pale_cyan, bg = c.near_black },
    PmenuExtra = { fg = c.medium_gray, bg = c.near_black },
    PmenuSbar = { bg = c.near_black },
    PmenuThumb = { bg = c.medium_dark_gray },
    StatusLine = { fg = c.muted_gray, bg = normal_bg },
    StatusLineNC = { fg = c.muted_gray, bg = normal_bg },
    TabLine = { fg = c.medium_gray, bg = c.near_black },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.icy_white, bg = c.medium_charcoal, bold = true },
    WinSeparator = { fg = c.light_blue_gray, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.charcoal_black, bg = c.vivid_orange, bold = true },
    Directory = { fg = c.light_cornflower_blue },
    Title = { fg = c.icy_white, bold = true },
    Question = { fg = c.pale_green },
    MoreMsg = { fg = c.pale_green },
    ModeMsg = { fg = c.warm_yellow, bold = true },
    WarningMsg = { fg = c.warm_yellow },
    ErrorMsg = { fg = c.vivid_pink_red },
    Error = { fg = c.vivid_pink_red },
    Todo = { fg = c.charcoal_black, bg = c.vivid_orange, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.deep_gray }, comment_style),
    SpecialComment = vim.tbl_extend("force", { fg = c.deep_gray }, comment_style),
    Constant = { fg = c.salmon_orange },
    String = { fg = c.pale_green },
    Character = { fg = c.pale_green },
    Number = { fg = c.salmon_orange },
    Boolean = { fg = c.salmon_orange, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.light_blue_gray },
    Function = { fg = c.light_cornflower_blue },
    Statement = vim.tbl_extend("force", { fg = c.light_violet }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.light_violet }, keyword_style),
    Operator = { fg = c.pale_cyan },
    Exception = { fg = c.light_violet },
    PreProc = { fg = c.pale_cyan },
    Include = { fg = c.pale_cyan },
    Define = { fg = c.pale_cyan },
    Macro = { fg = c.salmon_orange },
    Type = { fg = c.light_violet },
    StorageClass = { fg = c.light_violet },
    Structure = { fg = c.light_violet },
    Typedef = { fg = c.light_violet },
    Special = { fg = c.salmon_orange },
    Delimiter = { fg = c.pale_cyan },
    Underlined = { fg = c.muted_teal, underline = true },
    Ignore = { fg = c.medium_dark_gray },

    DiffAdd = { bg = c.near_black, fg = c.pale_green },
    DiffChange = { bg = c.near_black, fg = c.light_cornflower_blue },
    DiffDelete = { bg = c.near_black, fg = c.soft_red },
    DiffText = { bg = c.muted_charcoal, bold = true },
    Added = { fg = c.pale_green },
    Changed = { fg = c.light_cornflower_blue },
    Removed = { fg = c.soft_red },

    DiagnosticError = { fg = c.vivid_pink_red },
    DiagnosticWarn = { fg = c.warm_yellow },
    DiagnosticInfo = { fg = c.pale_periwinkle },
    DiagnosticHint = { fg = c.light_violet },
    DiagnosticOk = { fg = c.pale_green },
    DiagnosticUnderlineError = { sp = c.vivid_pink_red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.warm_yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.pale_periwinkle, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.light_violet, undercurl = true },
    LspReferenceText = { bg = c.muted_charcoal },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.muted_charcoal, underline = true },
    LspSignatureActiveParameter = { fg = c.vivid_orange, bold = true },
    LspCodeLens = { fg = c.deep_gray },

    SpellBad = { sp = c.vivid_pink_red, undercurl = true },
    SpellCap = { sp = c.warm_yellow, undercurl = true },
    SpellRare = { sp = c.light_violet, undercurl = true },
    SpellLocal = { sp = c.pale_cyan, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.salmon_orange },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.salmon_orange, bold = true },
    ["@constant.macro"] = { link = "Macro" },
    ["@variable"] = { fg = c.light_blue_gray },
    ["@variable.builtin"] = { fg = c.salmon_orange },
    ["@variable.parameter"] = { fg = c.pale_periwinkle },
    ["@variable.member"] = { fg = c.light_blue_gray },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.light_cornflower_blue },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.light_violet },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.pale_cyan },
    ["@punctuation.special"] = { fg = c.salmon_orange },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.light_violet, italic = true },
    ["@module"] = { fg = c.light_blue_gray },
    ["@property"] = { fg = c.light_blue_gray },
    ["@attribute"] = { fg = c.warm_yellow },
    ["@tag"] = { fg = c.soft_red },
    ["@tag.attribute"] = { fg = c.warm_yellow },
    ["@tag.delimiter"] = { fg = c.pale_cyan },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.muted_teal, underline = true },
    ["@markup.raw"] = { link = "String" },

    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.readonly"] = { link = "Constant" },

    GitSignsAdd = { fg = c.pale_green },
    GitSignsChange = { fg = c.light_cornflower_blue },
    GitSignsDelete = { fg = c.soft_red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.muted_charcoal, bold = true },
    TelescopeMatching = { fg = c.vivid_orange, bold = true },
    BlinkCmpLabelMatch = { fg = c.vivid_orange, bold = true },
    CmpItemAbbrMatch = { fg = c.vivid_orange, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.salmon_orange, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    PreCondit = "PreProc", Debug = "Special", SpecialChar = "Special",
    Tag = "Special", Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
