local M = {}

function M.setup(config)
  local c = require("md.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.bg
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.fg, bg = normal_bg },
    NormalNC = { fg = c.fg_dark, bg = normal_bg },
    NormalFloat = { fg = c.fg, bg = c.bg_alt },
    FloatBorder = { fg = c.border, bg = c.bg_alt },
    FloatTitle = { fg = c.title, bg = c.bg_alt, bold = true },
    Cursor = { fg = c.bg, bg = c.cursor },
    NonText = { fg = c.disabled },
    EndOfBuffer = { fg = c.bg },
    Whitespace = { fg = c.disabled },
    SpecialKey = { fg = c.line_numbers },
    LineNr = { fg = c.line_numbers, bg = normal_bg },
    CursorLineNr = { fg = c.accent, bg = normal_bg, bold = true },
    CursorLine = { bg = c.active },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.active },
    SignColumn = { fg = c.line_numbers, bg = normal_bg },
    CursorLineSign = { bg = c.active },
    FoldColumn = { fg = c.line_numbers, bg = normal_bg },
    Folded = { fg = c.fg_dark, bg = c.active },
    MatchParen = { fg = c.accent, bold = true },
    Visual = { bg = c.selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.bg, bg = c.accent },
    IncSearch = { fg = c.bg, bg = c.yellow },
    CurSearch = { fg = c.bg, bg = c.yellow, bold = true },
    Substitute = { fg = c.bg, bg = c.orange },
    Pmenu = { fg = c.fg, bg = c.bg_alt },
    PmenuSel = { fg = c.white, bg = c.highlight, bold = true },
    PmenuKind = { fg = c.cyan, bg = c.bg_alt },
    PmenuExtra = { fg = c.fg_dark, bg = c.bg_alt },
    PmenuSbar = { bg = c.bg_alt },
    PmenuThumb = { bg = c.disabled },
    StatusLine = { fg = c.fg_dark, bg = normal_bg },
    StatusLineNC = { fg = c.disabled, bg = normal_bg },
    TabLine = { fg = c.fg_dark, bg = c.bg_alt },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.white, bg = c.active, bold = true },
    WinSeparator = { fg = c.border, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.bg, bg = c.accent, bold = true },
    Directory = { fg = c.blue },
    Title = { fg = c.title, bold = true },
    Question = { fg = c.green },
    MoreMsg = { fg = c.green },
    ModeMsg = { fg = c.yellow, bold = true },
    WarningMsg = { fg = c.yellow },
    ErrorMsg = { fg = c.error },
    Error = { fg = c.error },
    Todo = { fg = c.bg, bg = c.accent, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.comments }, comment_style),
    SpecialComment = vim.tbl_extend("force", { fg = c.comments }, comment_style),
    Constant = { fg = c.orange },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue },
    Statement = vim.tbl_extend("force", { fg = c.purple }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.purple }, keyword_style),
    Operator = { fg = c.cyan },
    Exception = { fg = c.purple },
    PreProc = { fg = c.cyan },
    Include = { fg = c.cyan },
    Define = { fg = c.cyan },
    Macro = { fg = c.orange },
    Type = { fg = c.purple },
    StorageClass = { fg = c.purple },
    Structure = { fg = c.purple },
    Typedef = { fg = c.purple },
    Special = { fg = c.orange },
    Delimiter = { fg = c.cyan },
    Underlined = { fg = c.link, underline = true },
    Ignore = { fg = c.disabled },

    DiffAdd = { bg = c.contrast, fg = c.green },
    DiffChange = { bg = c.contrast, fg = c.blue },
    DiffDelete = { bg = c.contrast, fg = c.red },
    DiffText = { bg = c.highlight, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.blue },
    Removed = { fg = c.red },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.paleblue },
    DiagnosticHint = { fg = c.purple },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.paleblue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.purple, undercurl = true },
    LspReferenceText = { bg = c.highlight },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.highlight, underline = true },
    LspSignatureActiveParameter = { fg = c.accent, bold = true },
    LspCodeLens = { fg = c.comments },

    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.orange },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.orange, bold = true },
    ["@constant.macro"] = { link = "Macro" },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.orange },
    ["@variable.parameter"] = { fg = c.paleblue },
    ["@variable.member"] = { fg = c.fg },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.blue },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.purple },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.cyan },
    ["@punctuation.special"] = { fg = c.orange },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.purple, italic = true },
    ["@module"] = { fg = c.fg },
    ["@property"] = { fg = c.fg },
    ["@attribute"] = { fg = c.yellow },
    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.yellow },
    ["@tag.delimiter"] = { fg = c.cyan },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.link, underline = true },
    ["@markup.raw"] = { link = "String" },

    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.readonly"] = { link = "Constant" },

    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.blue },
    GitSignsDelete = { fg = c.red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.highlight, bold = true },
    TelescopeMatching = { fg = c.accent, bold = true },
    BlinkCmpLabelMatch = { fg = c.accent, bold = true },
    CmpItemAbbrMatch = { fg = c.accent, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.orange, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    PreCondit = "PreProc", Debug = "Special", SpecialChar = "Special",
    Tag = "Special", Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
