local M = {}

local function wave(c)
  return {
    ui = {
      fg = c.fujiWhite,
      fg_dim = c.oldWhite,
      fg_reverse = c.waveBlue1,
      bg_dim = c.sumiInk1,
      bg_gutter = c.sumiInk3,
      bg_m3 = c.sumiInk0,
      bg_m2 = c.sumiInk1,
      bg_m1 = c.sumiInk2,
      bg = c.sumiInk3,
      bg_p1 = c.sumiInk4,
      bg_p2 = c.sumiInk5,
      special = c.springViolet1,
      nontext = c.sumiInk6,
      whitespace = c.sumiInk6,
      bg_search = c.waveBlue2,
      bg_visual = c.waveBlue1,
      pmenu = {
        fg = c.fujiWhite,
        fg_sel = "none",
        bg = c.waveBlue1,
        bg_sel = c.waveBlue2,
        bg_sbar = c.waveBlue1,
        bg_thumb = c.waveBlue2,
      },
      float = {
        fg = c.oldWhite,
        bg = c.sumiInk0,
        fg_border = c.sumiInk6,
        bg_border = c.sumiInk0,
      },
    },
    syn = {
      string = c.springGreen,
      variable = "none",
      number = c.sakuraPink,
      constant = c.surimiOrange,
      identifier = c.carpYellow,
      parameter = c.oniViolet2,
      fun = c.crystalBlue,
      statement = c.oniViolet,
      keyword = c.oniViolet,
      operator = c.boatYellow2,
      preproc = c.waveRed,
      type = c.waveAqua2,
      regex = c.boatYellow2,
      deprecated = c.katanaGray,
      comment = c.fujiGray,
      punct = c.springViolet2,
      special1 = c.springBlue,
      special2 = c.waveRed,
      special3 = c.peachRed,
    },
    vcs = {
      added = c.autumnGreen,
      removed = c.autumnRed,
      changed = c.autumnYellow,
    },
    diff = {
      add = c.winterGreen,
      delete = c.winterRed,
      change = c.winterBlue,
      text = c.winterYellow,
    },
    diag = {
      ok = c.springGreen,
      error = c.samuraiRed,
      warning = c.roninYellow,
      info = c.dragonBlue,
      hint = c.waveAqua1,
    },
  }
end

local function style(config, old_key, kanagawa_key)
  if config.styles and config.styles[old_key] then
    return config.styles[old_key]
  end

  return config[kanagawa_key] or {}
end

function M.setup(config)
  local c = require("kg.palette")
  local theme = wave(c)
  local none = "NONE"
  local undercurl = config.undercurl ~= false
  local comment_style = style(config, "comments", "commentStyle")
  local function_style = config.functionStyle or {}
  local keyword_style = style(config, "keywords", "keywordStyle")
  local statement_style = config.statementStyle or {}
  local type_style = config.typeStyle or {}

  local g = {
    ColorColumn = { bg = theme.ui.bg_p1 },
    Conceal = { fg = theme.ui.special, bold = true },
    CurSearch = { fg = theme.ui.fg, bg = theme.ui.bg_search, bold = true },
    Cursor = { fg = theme.ui.bg, bg = theme.ui.fg },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorColumn = { link = "CursorLine" },
    CursorLine = { bg = theme.ui.bg_p2 },
    Directory = { fg = theme.syn.fun },
    DiffAdd = { bg = theme.diff.add },
    DiffChange = { bg = theme.diff.change },
    DiffDelete = { fg = theme.vcs.removed, bg = theme.diff.delete },
    DiffText = { bg = theme.diff.text },
    EndOfBuffer = { fg = theme.ui.bg },
    ErrorMsg = { fg = theme.diag.error },
    WinSeparator = { fg = theme.ui.nontext, bg = config.dimInactive and theme.ui.bg_dim or none },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = theme.ui.special, bg = theme.ui.bg_p1 },
    FoldColumn = { fg = theme.ui.nontext, bg = theme.ui.bg_gutter },
    SignColumn = { fg = theme.ui.special, bg = theme.ui.bg_gutter },
    IncSearch = { fg = theme.ui.fg_reverse, bg = theme.diag.warning },
    Substitute = { fg = theme.ui.fg, bg = theme.vcs.removed },
    LineNr = { fg = theme.ui.nontext, bg = theme.ui.bg_gutter },
    CursorLineNr = { fg = theme.diag.warning, bg = theme.ui.bg_gutter, bold = true },
    MatchParen = { fg = theme.diag.warning, bold = true },
    ModeMsg = { fg = theme.diag.warning, bold = true },
    MsgArea = vim.o.cmdheight == 0 and { link = "StatusLine" } or { fg = theme.ui.fg_dim },
    MsgSeparator = { bg = vim.o.cmdheight == 0 and theme.ui.bg or theme.ui.bg_m3, fg = theme.ui.bg_m3 },
    MoreMsg = { fg = theme.diag.info },
    NonText = { fg = theme.ui.nontext },
    Normal = { fg = theme.ui.fg, bg = not config.transparent and theme.ui.bg or none },
    NormalFloat = { fg = theme.ui.float.fg, bg = theme.ui.float.bg },
    FloatBorder = { fg = theme.ui.float.fg_border, bg = theme.ui.float.bg_border },
    FloatTitle = { fg = theme.ui.special, bg = theme.ui.float.bg_border, bold = true },
    FloatFooter = { fg = theme.ui.nontext, bg = theme.ui.float.bg_border },
    NormalNC = config.dimInactive and { fg = theme.ui.fg_dim, bg = theme.ui.bg_dim } or { link = "Normal" },
    Pmenu = { fg = theme.ui.pmenu.fg, bg = theme.ui.pmenu.bg },
    PmenuSel = { fg = theme.ui.pmenu.fg_sel, bg = theme.ui.pmenu.bg_sel },
    PmenuKind = { fg = theme.ui.fg_dim, bg = theme.ui.pmenu.bg },
    PmenuKindSel = { fg = theme.ui.fg_dim, bg = theme.ui.pmenu.bg_sel },
    PmenuExtra = { fg = theme.ui.special, bg = theme.ui.pmenu.bg },
    PmenuExtraSel = { fg = theme.ui.special, bg = theme.ui.pmenu.bg_sel },
    PmenuSbar = { bg = theme.ui.pmenu.bg_sbar },
    PmenuThumb = { bg = theme.ui.pmenu.bg_thumb },
    PmenuBorder = { link = "FloatBorder" },
    Question = { link = "MoreMsg" },
    QuickFixLine = { bg = theme.ui.bg_p1 },
    Search = { fg = theme.ui.fg, bg = theme.ui.bg_search },
    SpecialKey = { fg = theme.ui.special },
    SpellBad = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.error },
    SpellCap = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.warning },
    SpellLocal = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.warning },
    SpellRare = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.warning },
    StatusLine = { fg = theme.ui.nontext, bg = theme.ui.bg },
    StatusLineNC = { fg = theme.ui.nontext, bg = theme.ui.bg },
    TabLine = { bg = theme.ui.bg_m3, fg = theme.ui.special },
    TabLineFill = { bg = theme.ui.bg },
    TabLineSel = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
    Title = { fg = theme.syn.fun, bold = true },
    Visual = { bg = theme.ui.bg_visual },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = theme.diag.warning },
    Whitespace = { fg = theme.ui.whitespace },
    WildMenu = { link = "Pmenu" },
    WinBar = { fg = theme.ui.fg_dim, bg = none },
    WinBarNC = { fg = theme.ui.fg_dim, bg = config.dimInactive and theme.ui.bg_dim or none },

    Comment = vim.tbl_extend("force", { fg = theme.syn.comment }, comment_style),
    Constant = { fg = theme.syn.constant },
    String = { fg = theme.syn.string },
    Character = { link = "String" },
    Number = { fg = theme.syn.number },
    Boolean = { fg = theme.syn.constant, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = theme.syn.identifier },
    Function = vim.tbl_extend("force", { fg = theme.syn.fun }, function_style),
    Statement = vim.tbl_extend("force", { fg = theme.syn.statement }, statement_style),
    Operator = { fg = theme.syn.operator },
    Keyword = vim.tbl_extend("force", { fg = theme.syn.keyword }, keyword_style),
    Exception = { fg = theme.syn.special2 },
    PreProc = { fg = theme.syn.preproc },
    Type = vim.tbl_extend("force", { fg = theme.syn.type }, type_style),
    Special = { fg = theme.syn.special1 },
    Delimiter = { fg = theme.syn.punct },
    Underlined = { fg = theme.syn.special1, underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { link = "NonText" },
    Error = { fg = theme.diag.error },
    Todo = { fg = theme.ui.fg_reverse, bg = theme.diag.info, bold = true },
    qfLineNr = { link = "lineNr" },
    qfFileName = { link = "Directory" },
    markdownCode = { fg = theme.syn.string },
    markdownCodeBlock = { fg = theme.syn.string },
    markdownEscape = { fg = none },

    debugPC = { bg = theme.diff.delete },
    debugBreakpoint = { fg = theme.syn.special1, bg = theme.ui.bg_gutter },
    LspReferenceText = { bg = theme.diff.text },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = theme.diff.text, underline = true },
    LspSignatureActiveParameter = { fg = theme.diag.warning },
    LspCodeLens = { fg = theme.syn.comment },

    DiagnosticError = { fg = theme.diag.error },
    DiagnosticWarn = { fg = theme.diag.warning },
    DiagnosticInfo = { fg = theme.diag.info },
    DiagnosticHint = { fg = theme.diag.hint },
    DiagnosticOk = { fg = theme.diag.ok },
    DiagnosticFloatingError = { fg = theme.diag.error },
    DiagnosticFloatingWarn = { fg = theme.diag.warning },
    DiagnosticFloatingInfo = { fg = theme.diag.info },
    DiagnosticFloatingHint = { fg = theme.diag.hint },
    DiagnosticFloatingOk = { fg = theme.diag.ok },
    DiagnosticSignError = { fg = theme.diag.error, bg = theme.ui.bg_gutter },
    DiagnosticSignWarn = { fg = theme.diag.warning, bg = theme.ui.bg_gutter },
    DiagnosticSignInfo = { fg = theme.diag.info, bg = theme.ui.bg_gutter },
    DiagnosticSignHint = { fg = theme.diag.hint, bg = theme.ui.bg_gutter },
    DiagnosticVirtualTextError = { link = "DiagnosticError" },
    DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
    DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
    DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
    DiagnosticUnderlineError = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.error },
    DiagnosticUnderlineWarn = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.warning },
    DiagnosticUnderlineInfo = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.info },
    DiagnosticUnderlineHint = { undercurl = undercurl, underline = not undercurl, sp = theme.diag.hint },

    diffAdded = { fg = theme.vcs.added },
    diffRemoved = { fg = theme.vcs.removed },
    diffDeleted = { fg = theme.vcs.removed },
    diffChanged = { fg = theme.vcs.changed },
    diffOldFile = { fg = theme.vcs.removed },
    diffNewFile = { fg = theme.vcs.added },
    ["@variable"] = { fg = theme.ui.fg },
    ["@variable.builtin"] = { fg = theme.syn.special2, italic = true },
    ["@variable.parameter"] = { fg = theme.syn.parameter },
    ["@variable.member"] = { fg = theme.syn.identifier },
    ["@string.regexp"] = { fg = theme.syn.regex },
    ["@string.escape"] = { fg = theme.syn.regex, bold = true },
    ["@string.special.symbol"] = { fg = theme.syn.identifier },
    ["@string.special.url"] = { fg = theme.syn.special1, undercurl = true },
    ["@attribute"] = { link = "Constant" },
    ["@function.macro"] = { link = "Macro" },
    ["@constructor"] = { fg = theme.syn.special1 },
    ["@constructor.lua"] = { fg = theme.syn.keyword },
    ["@operator"] = { link = "Operator" },
    ["@keyword.operator"] = { fg = theme.syn.operator, bold = true },
    ["@keyword.import"] = { link = "PreProc" },
    ["@keyword.return"] = vim.tbl_extend("force", { fg = theme.syn.special3 }, keyword_style),
    ["@keyword.exception"] = vim.tbl_extend("force", { fg = theme.syn.special3 }, statement_style),
    ["@keyword.luap"] = { link = "@string.regex" },
    ["@punctuation.delimiter"] = { fg = theme.syn.punct },
    ["@punctuation.bracket"] = { fg = theme.syn.punct },
    ["@punctuation.special"] = { fg = theme.syn.special1 },
    ["@comment.error"] = { fg = theme.ui.fg, bg = theme.diag.error, bold = true },
    ["@comment.warning"] = { fg = theme.ui.fg_reverse, bg = theme.diag.warning, bold = true },
    ["@comment.note"] = { fg = theme.ui.fg_reverse, bg = theme.diag.hint, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { link = "Function" },
    ["@markup.quote"] = { link = "@variable.parameter" },
    ["@markup.math"] = { link = "Constant" },
    ["@markup.environment"] = { link = "Keyword" },
    ["@markup.link.url"] = { link = "@string.special.url" },
    ["@markup.raw"] = { link = "String" },
    ["@diff.plus"] = { fg = theme.vcs.added },
    ["@diff.minus"] = { fg = theme.vcs.removed },
    ["@diff.delta"] = { fg = theme.vcs.changed },
    ["@tag.attribute"] = { fg = theme.syn.identifier },
    ["@tag.delimiter"] = { fg = theme.syn.punct },

    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.variable"] = { fg = "none" },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.const"] = { link = "Constant" },
    ["@lsp.type.comparison"] = { link = "Operator" },
    ["@lsp.type.bitwise"] = { link = "Operator" },
    ["@lsp.type.punctuation"] = { link = "Delimiter" },
    ["@lsp.type.selfParameter"] = { link = "@variable.builtin" },
    ["@lsp.type.builtinConstant"] = { link = "@constant.builtin" },
    ["@lsp.type.magicFunction"] = { link = "@function.builtin" },
    ["@lsp.mod.readonly"] = { link = "Constant" },
    ["@lsp.mod.typeHint"] = { link = "Type" },
    ["@lsp.typemod.operator.controlFlow"] = { link = "@keyword.exception" },
    ["@lsp.type.lifetime"] = { link = "Operator" },
    ["@lsp.typemod.keyword.documentation"] = { link = "Special" },
    ["@lsp.type.decorator.rust"] = { link = "PreProc" },
    ["@lsp.typemod.variable.global"] = { link = "Constant" },
    ["@lsp.typemod.variable.static"] = { link = "Constant" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "Special" },
    ["@lsp.typemod.function.builtin"] = { link = "@function.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },
    ["@lsp.typemod.function.readonly"] = { fg = theme.syn.fun, bold = true },

    GitSignsAdd = { fg = theme.vcs.added, bg = theme.ui.bg_gutter },
    GitSignsChange = { fg = theme.vcs.changed, bg = theme.ui.bg_gutter },
    GitSignsDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_gutter },
    TreesitterContext = { link = "Folded" },
    TreesitterContextLineNumber = { fg = theme.ui.special, bg = theme.ui.bg_gutter },
    TelescopeBorder = { fg = "#FFFFFF", bg = theme.ui.bg },
    TelescopeTitle = { fg = theme.ui.special },
    TelescopeSelection = { link = "CursorLine" },
    TelescopeSelectionCaret = { link = "CursorLineNr" },
    TelescopeResultsClass = { link = "Structure" },
    TelescopeResultsStruct = { link = "Structure" },
    TelescopeResultsField = { link = "@field" },
    TelescopeResultsMethod = { link = "Function" },
    TelescopeResultsVariable = { link = "@variable" },

    CmpDocumentation = { link = "NormalFloat" },
    CmpDocumentationBorder = { link = "FloatBorder" },
    CmpCompletion = { link = "Pmenu" },
    CmpCompletionSel = { link = "PmenuSel" },
    CmpCompletionBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
    CmpCompletionThumb = { link = "PmenuThumb" },
    CmpCompletionSbar = { link = "PmenuSbar" },
    CmpItemAbbr = { fg = theme.ui.pmenu.fg },
    CmpItemAbbrDeprecated = { fg = theme.syn.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = theme.syn.fun },
    CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
    CmpItemKindDefault = { fg = theme.ui.fg_dim },
    CmpItemMenu = { fg = theme.ui.fg_dim },
    CmpGhostText = { fg = theme.syn.comment },
    CmpItemKindText = { fg = theme.ui.fg },
    CmpItemKindMethod = { link = "@function.method" },
    CmpItemKindFunction = { link = "Function" },
    CmpItemKindConstructor = { link = "@constructor" },
    CmpItemKindField = { link = "@variable.member" },
    CmpItemKindVariable = { fg = theme.ui.fg_dim },
    CmpItemKindClass = { link = "Type" },
    CmpItemKindInterface = { link = "Type" },
    CmpItemKindModule = { link = "@module" },
    CmpItemKindProperty = { link = "@property" },
    CmpItemKindUnit = { link = "Number" },
    CmpItemKindValue = { link = "String" },
    CmpItemKindEnum = { link = "Type" },
    CmpItemKindKeyword = { link = "Keyword" },
    CmpItemKindSnippet = { link = "Special" },
    CmpItemKindColor = { link = "Special" },
    CmpItemKindFile = { link = "Directory" },
    CmpItemKindReference = { link = "Special" },
    CmpItemKindFolder = { link = "Directory" },
    CmpItemKindEnumMember = { link = "Constant" },
    CmpItemKindConstant = { link = "Constant" },
    CmpItemKindStruct = { link = "Type" },
    CmpItemKindEvent = { link = "Type" },
    CmpItemKindOperator = { link = "Operator" },
    CmpItemKindTypeParameter = { link = "Type" },
    CmpItemKindCopilot = { link = "String" },

    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpMenuBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
    BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
    BlinkCmpLabelMatch = { fg = theme.syn.fun },
    BlinkCmpLabelDetails = { fg = theme.syn.comment },
    BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
    BlinkCmpGhostText = { fg = theme.syn.comment },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocCursorLine = { link = "Visual" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    BlinkCmpKind = { fg = theme.ui.fg_dim },
    BlinkCmpKindText = { fg = theme.ui.fg },
    BlinkCmpKindMethod = { link = "@function.method" },
    BlinkCmpKindFunction = { link = "Function" },
    BlinkCmpKindConstructor = { link = "@constructor" },
    BlinkCmpKindField = { link = "@variable.member" },
    BlinkCmpKindVariable = { fg = theme.ui.fg_dim },
    BlinkCmpKindClass = { link = "Type" },
    BlinkCmpKindInterface = { link = "Type" },
    BlinkCmpKindModule = { link = "@module" },
    BlinkCmpKindProperty = { link = "@property" },
    BlinkCmpKindUnit = { link = "Number" },
    BlinkCmpKindValue = { link = "String" },
    BlinkCmpKindEnum = { link = "Type" },
    BlinkCmpKindKeyword = { link = "Keyword" },
    BlinkCmpKindSnippet = { link = "Special" },
    BlinkCmpKindColor = { link = "Special" },
    BlinkCmpKindFile = { link = "Directory" },
    BlinkCmpKindReference = { link = "Special" },
    BlinkCmpKindFolder = { link = "Directory" },
    BlinkCmpKindEnumMember = { link = "Constant" },
    BlinkCmpKindConstant = { link = "Constant" },
    BlinkCmpKindStruct = { link = "Type" },
    BlinkCmpKindEvent = { link = "Type" },
    BlinkCmpKindOperator = { link = "Operator" },
    BlinkCmpKindTypeParameter = { link = "Type" },
    BlinkCmpKindCopilot = { link = "String" },
  }

  local links = {
    Conditional = "Statement",
    Repeat = "Statement",
    Label = "Statement",
    Include = "PreProc",
    Define = "PreProc",
    Macro = "PreProc",
    PreCondit = "PreProc",
    StorageClass = "Type",
    Structure = "Type",
    Typedef = "Type",
    Debug = "Special",
    SpecialChar = "Special",
    Tag = "Special",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
