local M = {}

function M.setup(config)
  local c = require("ay.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.near_black_blue
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.warm_light_gray, bg = normal_bg },
    NormalNC = { fg = c.medium_gray, bg = normal_bg },
    NormalFloat = { fg = c.warm_light_gray, bg = c.midnight_blue },
    FloatBorder = { fg = c.charcoal_blue_gray, bg = c.midnight_blue },
    FloatTitle = { fg = c.light_orange, bg = c.midnight_blue, bold = true },
    Cursor = { fg = c.near_black_blue, bg = c.light_orange },
    NonText = { fg = c.dark_blue_gray },
    EndOfBuffer = { fg = c.near_black_blue },
    Whitespace = { fg = c.dark_blue_gray },
    SpecialKey = { fg = c.blue_gray },
    LineNr = { fg = c.dark_blue_gray, bg = normal_bg },
    CursorLineNr = { fg = c.light_orange, bg = normal_bg, bold = true },
    CursorLine = { bg = c.charcoal_blue },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.charcoal_blue },
    SignColumn = { fg = c.dark_blue_gray, bg = normal_bg },
    CursorLineSign = { bg = c.charcoal_blue },
    FoldColumn = { fg = c.dark_blue_gray, bg = normal_bg },
    Folded = { fg = c.medium_gray, bg = c.charcoal_blue },
    MatchParen = { fg = c.mustard_yellow, bg = c.slate_blue, bold = true },
    Visual = { bg = c.slate_blue },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.near_black_blue, bg = c.pumpkin_orange, bold = true },
    IncSearch = { fg = c.near_black_blue, bg = c.light_orange, bold = true },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = c.near_black_blue, bg = c.vivid_red, bold = true },
    Pmenu = { fg = c.warm_light_gray, bg = c.midnight_blue },
    PmenuSel = { fg = c.near_black_blue, bg = c.light_orange, bold = true },
    PmenuKind = { fg = c.pumpkin_orange, bg = c.midnight_blue },
    PmenuExtra = { fg = c.blue_gray, bg = c.midnight_blue },
    PmenuSbar = { bg = c.midnight_blue },
    PmenuThumb = { bg = c.charcoal_blue_gray },
    StatusLine = { fg = c.medium_gray, bg = normal_bg },
    StatusLineNC = { fg = c.blue_gray, bg = normal_bg },
    TabLine = { fg = c.medium_gray, bg = c.midnight_blue },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.warm_light_gray, bg = c.charcoal_blue, bold = true },
    WinSeparator = { fg = c.charcoal_blue_gray, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.near_black_blue, bg = c.light_orange, bold = true },
    Directory = { fg = c.light_orange },
    Title = { fg = c.pumpkin_orange, bold = true },
    Question = { fg = c.pale_mint },
    MoreMsg = { fg = c.lime_green },
    ModeMsg = { fg = c.mustard_yellow, bold = true },
    WarningMsg = { fg = c.light_orange },
    ErrorMsg = { fg = c.vivid_red },
    Error = { fg = c.vivid_red },
    Todo = { fg = c.near_black_blue, bg = c.pumpkin_orange, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.blue_gray }, comment_style),
    SpecialComment = vim.tbl_extend("force", { fg = c.blue_gray }, comment_style),
    Constant = { fg = c.pumpkin_orange },
    String = { fg = c.lime_green },
    Character = { fg = c.lime_green },
    Number = { fg = c.light_orange },
    Boolean = { fg = c.light_orange, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.warm_light_gray },
    Function = { fg = c.mustard_yellow },
    Statement = vim.tbl_extend("force", { fg = c.light_orange }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.light_orange }, keyword_style),
    Operator = { fg = c.pumpkin_orange },
    Exception = { fg = c.vivid_red },
    PreProc = { fg = c.pale_lavender },
    Include = { fg = c.pale_lavender },
    Define = { fg = c.pale_lavender },
    Macro = { fg = c.pumpkin_orange },
    Type = { fg = c.pale_mint },
    StorageClass = { fg = c.light_orange },
    Structure = { fg = c.pale_mint },
    Typedef = { fg = c.pale_mint },
    Special = { fg = c.pumpkin_orange },
    Delimiter = { fg = c.medium_gray },
    Underlined = { fg = c.light_orange, underline = true },
    Ignore = { fg = c.dark_blue_gray },

    DiffAdd = { fg = c.lime_green },
    DiffChange = { fg = c.light_orange },
    DiffDelete = { fg = c.vivid_red },
    DiffText = { fg = c.near_black_blue, bg = c.pumpkin_orange, bold = true },
    Added = { link = "DiffAdd" },
    Changed = { link = "DiffChange" },
    Removed = { link = "DiffDelete" },

    DiagnosticError = { fg = c.vivid_red },
    DiagnosticWarn = { fg = c.light_orange },
    DiagnosticInfo = { fg = c.pale_mint },
    DiagnosticHint = { fg = c.pale_lavender },
    DiagnosticOk = { fg = c.lime_green },
    DiagnosticUnderlineError = { sp = c.vivid_red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.light_orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.pale_mint, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.pale_lavender, undercurl = true },
    LspReferenceText = { bg = c.slate_blue },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.slate_blue, underline = true },
    LspSignatureActiveParameter = { fg = c.light_orange, bold = true },
    LspCodeLens = { fg = c.blue_gray },

    SpellBad = { sp = c.vivid_red, undercurl = true },
    SpellCap = { sp = c.light_orange, undercurl = true },
    SpellRare = { sp = c.pale_lavender, undercurl = true },
    SpellLocal = { sp = c.pale_mint, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.pumpkin_orange },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.light_orange, bold = true },
    ["@constant.macro"] = { link = "Macro" },
    ["@variable"] = { fg = c.warm_light_gray },
    ["@variable.builtin"] = { fg = c.pumpkin_orange },
    ["@variable.parameter"] = { fg = c.mustard_yellow },
    ["@variable.member"] = { fg = c.medium_gray },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.mustard_yellow },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.pale_mint },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.medium_gray },
    ["@punctuation.special"] = { fg = c.pumpkin_orange },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.pale_mint, italic = true },
    ["@module"] = { fg = c.warm_light_gray },
    ["@property"] = { fg = c.light_orange },
    ["@property.yaml"] = { fg = c.light_orange, bold = true },
    ["@string.yaml"] = { fg = c.lime_green },
    ["@boolean.yaml"] = { fg = c.pumpkin_orange, bold = true },
    ["@number.yaml"] = { fg = c.pumpkin_orange },
    ["@attribute"] = { fg = c.pumpkin_orange },
    ["@tag"] = { fg = c.light_orange },
    ["@tag.attribute"] = { fg = c.pumpkin_orange },
    ["@tag.delimiter"] = { fg = c.medium_gray },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.light_orange, underline = true },
    ["@markup.raw"] = { link = "String" },
    ["@markup.list"] = { fg = c.light_orange },

    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },

    GitSignsAdd = { fg = c.lime_green },
    GitSignsChange = { fg = c.light_orange },
    GitSignsDelete = { fg = c.vivid_red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.slate_blue, bold = true },
    TelescopeMatching = { fg = c.light_orange, bold = true },
    BlinkCmpLabelMatch = { fg = c.light_orange, bold = true },
    CmpItemAbbrMatch = { fg = c.light_orange, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.pumpkin_orange, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    PreCondit = "PreProc", Debug = "Special", SpecialChar = "Special",
    Tag = "Special", Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
