local M = {}

function M.setup(config)
  local c = require("ay.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.bg
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.fg, bg = normal_bg },
    NormalNC = { fg = c.fg_dim, bg = normal_bg },
    NormalFloat = { fg = c.fg, bg = c.bg_alt },
    FloatBorder = { fg = c.border, bg = c.bg_alt },
    FloatTitle = { fg = c.orange, bg = c.bg_alt, bold = true },
    Cursor = { fg = c.bg, bg = c.orange },
    NonText = { fg = c.gutter },
    EndOfBuffer = { fg = c.bg },
    Whitespace = { fg = c.gutter },
    SpecialKey = { fg = c.comment },
    LineNr = { fg = c.gutter, bg = normal_bg },
    CursorLineNr = { fg = c.orange, bg = normal_bg, bold = true },
    CursorLine = { bg = c.bg_highlight },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.bg_highlight },
    SignColumn = { fg = c.gutter, bg = normal_bg },
    CursorLineSign = { bg = c.bg_highlight },
    FoldColumn = { fg = c.gutter, bg = normal_bg },
    Folded = { fg = c.fg_dim, bg = c.bg_highlight },
    MatchParen = { fg = c.amber, bg = c.bg_selection, bold = true },
    Visual = { bg = c.bg_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.bg, bg = c.pumpkin, bold = true },
    IncSearch = { fg = c.bg, bg = c.orange, bold = true },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = c.bg, bg = c.red, bold = true },
    Pmenu = { fg = c.fg, bg = c.bg_alt },
    PmenuSel = { fg = c.bg, bg = c.orange, bold = true },
    PmenuKind = { fg = c.pumpkin, bg = c.bg_alt },
    PmenuExtra = { fg = c.comment, bg = c.bg_alt },
    PmenuSbar = { bg = c.bg_alt },
    PmenuThumb = { bg = c.border },
    StatusLine = { fg = c.fg_dim, bg = normal_bg },
    StatusLineNC = { fg = c.comment, bg = normal_bg },
    TabLine = { fg = c.fg_dim, bg = c.bg_alt },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.fg, bg = c.bg_highlight, bold = true },
    WinSeparator = { fg = c.border, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.bg, bg = c.orange, bold = true },
    Directory = { fg = c.orange },
    Title = { fg = c.pumpkin, bold = true },
    Question = { fg = c.teal },
    MoreMsg = { fg = c.green },
    ModeMsg = { fg = c.amber, bold = true },
    WarningMsg = { fg = c.orange },
    ErrorMsg = { fg = c.red },
    Error = { fg = c.red },
    Todo = { fg = c.bg, bg = c.pumpkin, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.comment }, comment_style),
    SpecialComment = vim.tbl_extend("force", { fg = c.comment }, comment_style),
    Constant = { fg = c.pumpkin },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.fg },
    Function = { fg = c.amber },
    Statement = vim.tbl_extend("force", { fg = c.orange }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.orange }, keyword_style),
    Operator = { fg = c.pumpkin },
    Exception = { fg = c.red },
    PreProc = { fg = c.purple },
    Include = { fg = c.purple },
    Define = { fg = c.purple },
    Macro = { fg = c.pumpkin },
    Type = { fg = c.teal },
    StorageClass = { fg = c.orange },
    Structure = { fg = c.teal },
    Typedef = { fg = c.teal },
    Special = { fg = c.pumpkin },
    Delimiter = { fg = c.fg_dim },
    Underlined = { fg = c.orange, underline = true },
    Ignore = { fg = c.gutter },

    DiffAdd = { fg = c.green },
    DiffChange = { fg = c.orange },
    DiffDelete = { fg = c.red },
    DiffText = { fg = c.bg, bg = c.pumpkin, bold = true },
    Added = { link = "DiffAdd" },
    Changed = { link = "DiffChange" },
    Removed = { link = "DiffDelete" },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.teal },
    DiagnosticHint = { fg = c.purple },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.teal, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.purple, undercurl = true },
    LspReferenceText = { bg = c.bg_selection },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.bg_selection, underline = true },
    LspSignatureActiveParameter = { fg = c.orange, bold = true },
    LspCodeLens = { fg = c.comment },

    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.orange, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
    SpellLocal = { sp = c.teal, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.pumpkin },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.orange, bold = true },
    ["@constant.macro"] = { link = "Macro" },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.pumpkin },
    ["@variable.parameter"] = { fg = c.amber },
    ["@variable.member"] = { fg = c.fg_dim },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.amber },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.teal },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.fg_dim },
    ["@punctuation.special"] = { fg = c.pumpkin },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.teal, italic = true },
    ["@module"] = { fg = c.fg },
    ["@property"] = { fg = c.orange },
    ["@property.yaml"] = { fg = c.orange, bold = true },
    ["@string.yaml"] = { fg = c.green },
    ["@boolean.yaml"] = { fg = c.pumpkin, bold = true },
    ["@number.yaml"] = { fg = c.pumpkin },
    ["@attribute"] = { fg = c.pumpkin },
    ["@tag"] = { fg = c.orange },
    ["@tag.attribute"] = { fg = c.pumpkin },
    ["@tag.delimiter"] = { fg = c.fg_dim },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.orange, underline = true },
    ["@markup.raw"] = { link = "String" },
    ["@markup.list"] = { fg = c.orange },

    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },

    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.orange },
    GitSignsDelete = { fg = c.red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.bg_selection, bold = true },
    TelescopeMatching = { fg = c.orange, bold = true },
    BlinkCmpLabelMatch = { fg = c.orange, bold = true },
    CmpItemAbbrMatch = { fg = c.orange, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.pumpkin, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    PreCondit = "PreProc", Debug = "Special", SpecialChar = "Special",
    Tag = "Special", Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
