local M = {}

function M.setup(config)
  local c = require("dc.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.dark_charcoal_blue
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.soft_white, bg = normal_bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.soft_white, bg = c.near_black_blue },
    FloatBorder = { fg = c.muted_cornflower, bg = c.near_black_blue },
    FloatTitle = { fg = c.light_violet, bg = c.near_black_blue, bold = true },
    NonText = { fg = c.muted_cornflower },
    EndOfBuffer = { fg = c.dark_charcoal_blue },
    Whitespace = { fg = c.muted_indigo_gray },
    LineNr = { fg = c.muted_cornflower, bg = normal_bg },
    CursorLineNr = { fg = c.pale_yellow, bg = normal_bg, bold = true },
    CursorLine = { bg = c.muted_indigo_gray },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.dark_indigo_gray },
    SignColumn = { fg = c.light_violet, bg = normal_bg },
    CursorLineSign = { bg = c.muted_indigo_gray },
    FoldColumn = { fg = c.muted_cornflower, bg = normal_bg },
    Folded = { fg = c.muted_cornflower, bg = c.dark_indigo_gray },
    MatchParen = { fg = c.pale_yellow, bold = true },
    Visual = { bg = c.muted_indigo_gray },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.dark_charcoal_blue, bg = c.light_orange },
    IncSearch = { fg = c.dark_charcoal_blue, bg = c.pale_yellow },
    CurSearch = { fg = c.dark_charcoal_blue, bg = c.pale_yellow, bold = true },
    Substitute = { fg = c.dark_charcoal_blue, bg = c.coral_red },
    Pmenu = { fg = c.soft_white, bg = c.near_black_blue },
    PmenuSel = { fg = c.soft_white, bg = c.muted_indigo_gray, bold = true },
    PmenuKind = { fg = c.pale_cyan, bg = c.near_black_blue },
    PmenuExtra = { fg = c.muted_cornflower, bg = c.near_black_blue },
    PmenuSbar = { bg = c.dark_indigo_gray },
    PmenuThumb = { bg = c.muted_cornflower },
    StatusLine = { fg = c.muted_cornflower, bg = normal_bg },
    StatusLineNC = { fg = c.muted_cornflower, bg = normal_bg },
    TabLine = { fg = c.muted_cornflower, bg = c.near_black_blue },
    TabLineFill = { bg = c.dark_charcoal_blue },
    TabLineSel = { fg = c.soft_white, bg = c.muted_indigo_gray },
    WinSeparator = { fg = c.muted_cornflower },
    VertSplit = { link = "WinSeparator" },
    Directory = { fg = c.pale_cyan },
    Title = { fg = c.light_violet, bold = true },
    Question = { fg = c.pale_cyan },
    MoreMsg = { fg = c.bright_green },
    ModeMsg = { fg = c.pale_yellow, bold = true },
    WarningMsg = { fg = c.light_orange },
    ErrorMsg = { fg = c.coral_red },
    Error = { fg = c.coral_red },
    Todo = { fg = c.dark_charcoal_blue, bg = c.pale_yellow, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.muted_cornflower }, comment_style),
    SpecialComment = { fg = c.muted_cornflower, bold = true },
    Constant = { fg = c.light_violet },
    String = { fg = c.pale_yellow },
    Character = { fg = c.bright_pink },
    Number = { fg = c.light_violet },
    Boolean = { fg = c.light_violet, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.soft_white },
    Function = { fg = c.bright_green },
    Statement = vim.tbl_extend("force", { fg = c.bright_pink, bold = true }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.bright_pink }, keyword_style),
    Operator = { fg = c.bright_pink },
    Exception = { fg = c.bright_pink },
    PreProc = { fg = c.bright_pink },
    Type = { fg = c.pale_cyan },
    Special = { fg = c.light_orange },
    Delimiter = { fg = c.soft_white },
    Underlined = { fg = c.pale_cyan, underline = true },

    DiffAdd = { bg = c.dark_forest_green },
    DiffChange = { bg = c.dark_slate_blue },
    DiffDelete = { fg = c.coral_red, bg = c.dark_burgundy },
    DiffText = { fg = c.soft_white, bg = c.muted_indigo_gray, bold = true },
    Added = { fg = c.bright_green },
    Changed = { fg = c.light_orange },
    Removed = { fg = c.coral_red },

    DiagnosticError = { fg = c.coral_red },
    DiagnosticWarn = { fg = c.light_orange },
    DiagnosticInfo = { fg = c.pale_cyan },
    DiagnosticHint = { fg = c.light_violet },
    DiagnosticOk = { fg = c.bright_green },
    DiagnosticUnderlineError = { sp = c.coral_red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.light_orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.pale_cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.light_violet, undercurl = true },
    LspReferenceText = { bg = c.muted_indigo_gray },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.muted_indigo_gray, underline = true },
    LspSignatureActiveParameter = { fg = c.pale_yellow, bold = true },
    LspCodeLens = { fg = c.muted_cornflower },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.bright_pink },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.light_violet, bold = true },
    ["@variable"] = { fg = c.soft_white },
    ["@variable.builtin"] = { fg = c.light_violet, italic = true },
    ["@variable.parameter"] = { fg = c.light_orange },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.pale_cyan },
    ["@function.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.pale_cyan },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.bright_pink },
    ["@keyword.return"] = { fg = c.bright_pink },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.pale_cyan, italic = true },
    ["@property"] = { fg = c.pale_cyan },
    ["@attribute"] = { fg = c.bright_green },
    ["@tag"] = { fg = c.bright_pink },
    ["@tag.attribute"] = { fg = c.bright_green },
    ["@tag.delimiter"] = { fg = c.soft_white },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.pale_cyan, underline = true },
    ["@markup.raw"] = { link = "String" },

    GitSignsAdd = { fg = c.bright_green },
    GitSignsChange = { fg = c.light_orange },
    GitSignsDelete = { fg = c.coral_red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.muted_indigo_gray, bold = true },
    TelescopeMatching = { fg = c.pale_yellow, bold = true },
    BlinkCmpLabelMatch = { fg = c.bright_green, bold = true },
    CmpItemAbbrMatch = { fg = c.bright_green, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.pale_cyan, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    Include = "PreProc", Define = "PreProc", Macro = "PreProc", PreCondit = "PreProc",
    StorageClass = "Type", Structure = "Type", Typedef = "Type",
    Debug = "Special", SpecialChar = "Special", Tag = "Special", Terminal = "Normal",
    QuickFixLine = "Search", SpellBad = "DiagnosticUnderlineError",
    SpellCap = "DiagnosticUnderlineWarn", SpellLocal = "DiagnosticUnderlineInfo",
    SpellRare = "DiagnosticUnderlineHint",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
