local M = {}

function M.setup(config)
  local c = require("dc.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.background
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.foreground, bg = normal_bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.foreground, bg = c.menu },
    FloatBorder = { fg = c.comment, bg = c.menu },
    FloatTitle = { fg = c.purple, bg = c.menu, bold = true },
    NonText = { fg = c.comment },
    EndOfBuffer = { fg = c.background },
    Whitespace = { fg = c.current_line },
    LineNr = { fg = c.comment, bg = normal_bg },
    CursorLineNr = { fg = c.yellow, bg = normal_bg, bold = true },
    CursorLine = { bg = c.current_line },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.subtle },
    SignColumn = { fg = c.purple, bg = normal_bg },
    CursorLineSign = { bg = c.current_line },
    FoldColumn = { fg = c.comment, bg = normal_bg },
    Folded = { fg = c.comment, bg = c.subtle },
    MatchParen = { fg = c.yellow, bold = true },
    Visual = { bg = c.selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.background, bg = c.orange },
    IncSearch = { fg = c.background, bg = c.yellow },
    CurSearch = { fg = c.background, bg = c.yellow, bold = true },
    Substitute = { fg = c.background, bg = c.red },
    Pmenu = { fg = c.foreground, bg = c.menu },
    PmenuSel = { fg = c.foreground, bg = c.current_line, bold = true },
    PmenuKind = { fg = c.cyan, bg = c.menu },
    PmenuExtra = { fg = c.comment, bg = c.menu },
    PmenuSbar = { bg = c.subtle },
    PmenuThumb = { bg = c.comment },
    StatusLine = { fg = c.comment, bg = normal_bg },
    StatusLineNC = { fg = c.comment, bg = normal_bg },
    TabLine = { fg = c.comment, bg = c.menu },
    TabLineFill = { bg = c.background },
    TabLineSel = { fg = c.foreground, bg = c.current_line },
    WinSeparator = { fg = c.comment },
    VertSplit = { link = "WinSeparator" },
    Directory = { fg = c.cyan },
    Title = { fg = c.purple, bold = true },
    Question = { fg = c.cyan },
    MoreMsg = { fg = c.green },
    ModeMsg = { fg = c.yellow, bold = true },
    WarningMsg = { fg = c.orange },
    ErrorMsg = { fg = c.red },
    Error = { fg = c.red },
    Todo = { fg = c.background, bg = c.yellow, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.comment }, comment_style),
    SpecialComment = { fg = c.comment, bold = true },
    Constant = { fg = c.purple },
    String = { fg = c.yellow },
    Character = { fg = c.pink },
    Number = { fg = c.purple },
    Boolean = { fg = c.purple, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.foreground },
    Function = { fg = c.green },
    Statement = vim.tbl_extend("force", { fg = c.pink, bold = true }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.pink }, keyword_style),
    Operator = { fg = c.pink },
    Exception = { fg = c.pink },
    PreProc = { fg = c.pink },
    Type = { fg = c.cyan },
    Special = { fg = c.orange },
    Delimiter = { fg = c.foreground },
    Underlined = { fg = c.cyan, underline = true },

    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { fg = c.red, bg = c.diff_delete },
    DiffText = { fg = c.foreground, bg = c.current_line, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.orange },
    Removed = { fg = c.red },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.cyan },
    DiagnosticHint = { fg = c.purple },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.purple, undercurl = true },
    LspReferenceText = { bg = c.current_line },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.current_line, underline = true },
    LspSignatureActiveParameter = { fg = c.yellow, bold = true },
    LspCodeLens = { fg = c.comment },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.pink },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.purple, bold = true },
    ["@variable"] = { fg = c.foreground },
    ["@variable.builtin"] = { fg = c.purple, italic = true },
    ["@variable.parameter"] = { fg = c.orange },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.cyan },
    ["@function.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.cyan },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.pink },
    ["@keyword.return"] = { fg = c.pink },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.cyan, italic = true },
    ["@property"] = { fg = c.cyan },
    ["@attribute"] = { fg = c.green },
    ["@tag"] = { fg = c.pink },
    ["@tag.attribute"] = { fg = c.green },
    ["@tag.delimiter"] = { fg = c.foreground },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.cyan, underline = true },
    ["@markup.raw"] = { link = "String" },

    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.orange },
    GitSignsDelete = { fg = c.red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.current_line, bold = true },
    TelescopeMatching = { fg = c.yellow, bold = true },
    BlinkCmpLabelMatch = { fg = c.green, bold = true },
    CmpItemAbbrMatch = { fg = c.green, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.cyan, bold = true },
  }

  local links = {
    Conditional = "Statement", Repeat = "Statement", Label = "Statement",
    Include = "PreProc", Define = "PreProc", Macro = "PreProc", PreCondit = "PreProc",
    StorageClass = "Type", Structure = "Type", Typedef = "Type",
    Debug = "Special", SpecialChar = "Special", Tag = "Special", Terminal = "Normal",
    QuickFixLine = "Search", SpellBad = "DiagnosticUnderlineError",
    SpellCap = "DiagnosticUnderlineWarn", SpellLocal = "DiagnosticUnderlineInfo",
    SpellRare = "DiagnosticUnderlineHint",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
