local M = {}

function M.setup(config)
  local c = require("oc.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.retro_black
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.light_gray, bg = normal_bg },
    NormalNC = { fg = c.light_gray, bg = normal_bg },
    NormalFloat = { fg = c.soft_white, bg = c.deep_charcoal },
    FloatBorder = { fg = c.medium_charcoal, bg = c.deep_charcoal },
    FloatTitle = { fg = c.soft_white, bg = c.deep_charcoal, bold = true },
    ColorColumn = { bg = c.charcoal_black },
    Conceal = { fg = c.medium_gray },
    CurSearch = { fg = c.near_black, bg = c.bright_yellow },
    Cursor = { fg = c.near_black, bg = c.soft_white },
    CursorColumn = { bg = c.charcoal_black },
    CursorLine = { bg = c.charcoal_black },
    CursorLineNr = { fg = c.soft_white, bold = true },
    CursorLineSign = { link = "CursorLine" },
    Directory = { fg = c.light_cornflower_blue },
    DiffAdd = { bg = c.dark_forest_green },
    DiffChange = { bg = c.dark_navy_blue },
    DiffDelete = { bg = c.dark_maroon },
    DiffText = { bg = c.deep_forest_green },
    EndOfBuffer = { fg = c.near_black },
    ErrorMsg = { fg = c.bright_red_orange },
    FoldColumn = { fg = c.dark_gray },
    Folded = { fg = c.medium_gray, bg = c.charcoal_black },
    IncSearch = { fg = c.near_black, bg = c.pale_orange },
    LineNr = { fg = c.dark_gray },
    MatchParen = { fg = c.pale_orange, bold = true },
    ModeMsg = { fg = c.soft_white, bold = true },
    MoreMsg = { fg = c.vivid_green },
    MsgArea = { fg = c.light_gray },
    MsgSeparator = { fg = c.medium_charcoal, bg = c.near_black },
    NonText = { fg = c.dark_gray },
    Pmenu = { fg = c.soft_white, bg = c.deep_charcoal },
    PmenuSel = { fg = c.near_black, bg = c.light_cornflower_blue, bold = true },
    PmenuKind = { fg = c.medium_gray, bg = c.deep_charcoal },
    PmenuExtra = { fg = c.medium_gray, bg = c.deep_charcoal },
    PmenuSbar = { bg = c.deep_charcoal },
    PmenuThumb = { bg = c.medium_charcoal },
    Question = { fg = c.vivid_green },
    QuickFixLine = { bg = c.dark_charcoal, bold = true },
    Search = { fg = c.near_black, bg = c.bright_yellow },
    SignColumn = { fg = c.dark_gray, bg = normal_bg },
    SpecialKey = { fg = c.dark_gray },
    StatusLine = { fg = c.dark_gray, bg = normal_bg },
    StatusLineNC = { fg = c.dark_gray, bg = normal_bg },
    Substitute = { fg = c.near_black, bg = c.pale_orange },
    TabLine = { fg = c.medium_gray, bg = c.charcoal_black },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.soft_white, bg = normal_bg, bold = true },
    Title = { fg = c.soft_white, bold = true },
    Visual = { bg = c.charcoal_gray },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = c.bright_yellow },
    Whitespace = { fg = c.dark_gray },
    WildMenu = { link = "PmenuSel" },
    WinSeparator = { fg = c.dark_gray },

    Comment = vim.tbl_extend("force", { fg = c.medium_gray }, comment_style),
    Constant = { fg = c.pale_cyan },
    String = { fg = c.vivid_teal },
    Character = { fg = c.vivid_teal },
    Number = { fg = c.pale_cyan },
    Boolean = { fg = c.pale_orange },
    Float = { fg = c.pale_orange },
    Identifier = { fg = c.soft_white },
    Function = { fg = c.light_cornflower_blue },
    Statement = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Conditional = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Repeat = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Label = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Operator = { fg = c.medium_gray },
    Keyword = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Exception = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    PreProc = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Include = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Define = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Macro = { fg = c.pale_orange },
    PreCondit = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Type = { fg = c.bright_yellow },
    StorageClass = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    Structure = { fg = c.bright_yellow },
    Typedef = { fg = c.bright_yellow },
    Special = { fg = c.pale_orange },
    SpecialChar = { fg = c.pale_orange },
    Tag = { fg = c.medium_gray },
    Delimiter = { fg = c.medium_gray },
    SpecialComment = vim.tbl_extend("force", { fg = c.medium_gray }, comment_style),
    Debug = { fg = c.pale_orange },
    Underlined = { underline = true },
    Ignore = { fg = c.dark_gray },
    Error = { fg = c.bright_red_orange },
    Todo = { fg = c.pale_cyan, bold = true },
    Added = { fg = c.vivid_green },
    Changed = { fg = c.light_cornflower_blue },
    Removed = { fg = c.bright_red_orange },

    DiagnosticError = { fg = c.bright_red_orange },
    DiagnosticWarn = { fg = c.bright_yellow },
    DiagnosticInfo = { fg = c.light_cornflower_blue },
    DiagnosticHint = { fg = c.vivid_green },
    DiagnosticOk = { fg = c.vivid_green },
    DiagnosticVirtualTextError = { fg = c.bright_red_orange, bg = c.dark_red_black },
    DiagnosticVirtualTextWarn = { fg = c.bright_yellow, bg = c.dark_olive_black },
    DiagnosticVirtualTextInfo = { fg = c.light_cornflower_blue, bg = c.dark_blue_gray },
    DiagnosticVirtualTextHint = { fg = c.vivid_green, bg = c.dark_green_black },
    DiagnosticUnderlineError = { undercurl = true, sp = c.bright_red_orange },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.bright_yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.light_cornflower_blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.vivid_green },
    LspReferenceText = { bg = c.charcoal_gray },
    LspReferenceRead = { bg = c.charcoal_gray },
    LspReferenceWrite = { bg = c.charcoal_gray },
    LspSignatureActiveParameter = { fg = c.pale_orange, bold = true },
    LspCodeLens = { fg = c.dark_gray },
    LspInlayHint = { fg = c.dark_gray, bg = c.charcoal_black },

    ["@variable"] = { fg = c.soft_white },
    ["@variable.builtin"] = { fg = c.pale_orange },
    ["@variable.parameter"] = { fg = c.soft_white },
    ["@variable.member"] = { fg = c.medium_gray },
    ["@constant"] = { fg = c.pale_cyan },
    ["@constant.builtin"] = { fg = c.pale_orange },
    ["@constant.macro"] = { fg = c.pale_orange },
    ["@module"] = { fg = c.bright_yellow },
    ["@module.builtin"] = { fg = c.pale_orange },
    ["@label"] = { fg = c.medium_gray },
    ["@string"] = { fg = c.vivid_teal },
    ["@string.documentation"] = { fg = c.medium_gray },
    ["@string.regexp"] = { fg = c.light_gray },
    ["@string.escape"] = { fg = c.pale_orange },
    ["@string.special"] = { fg = c.pale_orange },
    ["@character"] = { fg = c.vivid_teal },
    ["@character.special"] = { fg = c.pale_orange },
    ["@boolean"] = { fg = c.pale_cyan },
    ["@number"] = { fg = c.pale_cyan },
    ["@number.float"] = { fg = c.pale_orange },
    ["@type"] = { fg = c.bright_yellow },
    ["@type.builtin"] = { fg = c.bright_yellow },
    ["@type.definition"] = { fg = c.bright_yellow },
    ["@attribute"] = { fg = c.medium_gray },
    ["@property"] = { fg = c.medium_gray },
    ["@function"] = { fg = c.light_cornflower_blue },
    ["@function.builtin"] = { fg = c.light_cornflower_blue },
    ["@function.call"] = { fg = c.light_cornflower_blue },
    ["@function.macro"] = { fg = c.light_cornflower_blue },
    ["@function.method"] = { fg = c.light_cornflower_blue },
    ["@function.method.call"] = { fg = c.light_cornflower_blue },
    ["@constructor"] = { fg = c.bright_yellow },
    ["@operator"] = { fg = c.medium_gray },
    ["@keyword"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.function"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.operator"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.import"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.type"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.repeat"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.return"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.exception"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.conditional"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.directive"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@keyword.directive.define"] = vim.tbl_extend("force", { fg = c.pale_violet }, keyword_style),
    ["@punctuation.delimiter"] = { fg = c.medium_gray },
    ["@punctuation.bracket"] = { fg = c.medium_gray },
    ["@punctuation.special"] = { fg = c.medium_gray },
    ["@comment"] = vim.tbl_extend("force", { fg = c.medium_gray }, comment_style),
    ["@comment.documentation"] = vim.tbl_extend("force", { fg = c.medium_gray }, comment_style),
    ["@comment.error"] = { fg = c.bright_red_orange },
    ["@comment.warning"] = { fg = c.bright_yellow },
    ["@comment.todo"] = { fg = c.pale_cyan, bold = true },
    ["@comment.note"] = { fg = c.pale_cyan },
    ["@lsp.type.class"] = { fg = c.bright_yellow },
    ["@lsp.type.decorator"] = { fg = c.medium_gray },
    ["@lsp.type.enum"] = { fg = c.bright_yellow },
    ["@lsp.type.enumMember"] = { fg = c.pale_cyan },
    ["@lsp.type.function"] = { fg = c.light_cornflower_blue },
    ["@lsp.type.interface"] = { fg = c.bright_yellow },
    ["@lsp.type.macro"] = { fg = c.light_cornflower_blue },
    ["@lsp.type.method"] = { fg = c.light_cornflower_blue },
    ["@lsp.type.namespace"] = { fg = c.dark_gray },
    ["@lsp.type.parameter"] = { fg = c.soft_white },
    ["@lsp.type.property"] = { fg = c.soft_white },
    ["@lsp.type.struct"] = { fg = c.bright_yellow },
    ["@lsp.type.type"] = { fg = c.bright_yellow },
    ["@lsp.type.typeParameter"] = { fg = c.bright_yellow },
    ["@lsp.type.variable"] = { fg = c.soft_white },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.readonly"] = { fg = c.soft_white },
    ["@markup.heading"] = { fg = c.pale_cyan, bold = true },
    ["@markup.link"] = { fg = c.pale_orange },
    ["@markup.link.url"] = { fg = c.pale_orange, underline = true },
    ["@markup.raw"] = { fg = c.vivid_teal },
    ["@markup.list"] = { fg = c.pale_orange },
    ["@tag"] = { fg = c.medium_gray },
    ["@tag.attribute"] = { fg = c.pale_orange },
    ["@tag.delimiter"] = { fg = c.medium_gray },
    ["@tag.builtin"] = { fg = c.vivid_teal },

    GitSignsAdd = { fg = c.vivid_green },
    GitSignsChange = { fg = c.pale_orange },
    GitSignsDelete = { fg = c.bright_red_orange },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.light_cornflower_blue },
    TelescopeMatching = { fg = c.pale_orange, bold = true },
    BlinkCmpLabelMatch = { fg = c.soft_white, bold = true },
    CmpItemAbbrMatch = { fg = c.soft_white, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.soft_white, bold = true },
  }

  local links = {
    Terminal = "Normal",
    lCursor = "Cursor",
    CursorIM = "Cursor",
    LineNrAbove = "LineNr",
    LineNrBelow = "LineNr",
    CursorLineFold = "CursorLineNr",
    SpellBad = "DiagnosticUnderlineError",
    SpellCap = "DiagnosticUnderlineWarn",
    SpellLocal = "DiagnosticUnderlineInfo",
    SpellRare = "DiagnosticUnderlineHint",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
