local M = {}

function M.setup(config)
  local c = require("gn.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.background
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.foreground, bg = normal_bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.foreground, bg = c.background_alt },
    FloatBorder = { fg = c.comment, bg = c.background_alt },
    FloatTitle = { fg = c.green_bright, bg = c.background_alt, bold = true },
    Cursor = { fg = c.black, bg = c.green_bright },
    NonText = { fg = c.nontext },
    EndOfBuffer = { fg = c.background },
    Whitespace = { fg = c.nontext },
    SpecialKey = { fg = c.yellow_dark },
    LineNr = { fg = c.foreground_dim, bg = normal_bg },
    CursorLineNr = { fg = c.green_bright, bg = normal_bg, bold = true },
    CursorLine = { bg = c.background_alt },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.background_alt },
    SignColumn = { fg = c.cyan, bg = normal_bg },
    CursorLineSign = { bg = c.background_alt },
    FoldColumn = { fg = c.foreground, bg = c.black },
    Folded = { fg = c.yellow_dark, bg = c.black },
    MatchParen = { fg = c.white, bg = c.green_dark, bold = true },
    Visual = { fg = c.visual, bg = c.white },
    VisualNOS = { fg = c.foreground, bg = c.black, underline = true },
    Search = { fg = c.foreground, bg = c.red_dark },
    IncSearch = { fg = c.black, bg = c.green_bright },
    CurSearch = { fg = c.black, bg = c.green_bright, bold = true },
    Substitute = { fg = c.foreground, bg = c.red_dark },
    Pmenu = { fg = c.foreground, bg = c.background_alt },
    PmenuSel = { fg = c.purple, bg = c.black, bold = true },
    PmenuKind = { fg = c.green_bright, bg = c.background_alt },
    PmenuExtra = { fg = c.foreground_dim, bg = c.background_alt },
    PmenuSbar = { bg = c.black },
    PmenuThumb = { bg = c.background_light },
    StatusLine = { fg = c.foreground_dim, bg = normal_bg, bold = true },
    StatusLineNC = { fg = c.foreground_dim, bg = normal_bg },
    TabLine = { fg = c.foreground_dim, bg = c.background_light },
    TabLineFill = { bg = c.background },
    TabLineSel = { fg = c.foreground, bg = c.background_alt, bold = true },
    WinSeparator = { fg = c.foreground, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.purple_bright, bg = c.black, bold = true },
    Directory = { fg = c.green_bright },
    Title = { fg = c.red, bold = true },
    Question = { fg = c.foreground },
    MoreMsg = { fg = c.foreground, bold = true },
    ModeMsg = { fg = c.foreground, bold = true },
    WarningMsg = { fg = c.foreground, bg = c.red_dark },
    ErrorMsg = { fg = c.foreground, bg = c.red_dark },
    Error = { fg = c.error, bg = c.black },
    Todo = { fg = c.foreground, bg = c.red_dark, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.comment }, comment_style),
    SpecialComment = { fg = c.comment, bold = true },
    Constant = { fg = c.yellow },
    String = { fg = c.green_string, bg = c.green_string_bg },
    Character = { link = "String" },
    Number = { fg = c.orange },
    Boolean = { fg = c.green_bright, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.cyan },
    Function = { fg = c.cyan },
    Statement = vim.tbl_extend("force", { fg = c.green }, keyword_style),
    Conditional = vim.tbl_extend("force", { fg = c.magenta }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.blue }, keyword_style),
    Operator = { fg = c.green },
    Exception = { fg = c.magenta },
    PreProc = { fg = c.red },
    Type = { fg = c.purple },
    Special = { fg = c.peach },
    Delimiter = { fg = c.purple_dim },
    Underlined = { fg = c.foreground, underline = true },
    Ignore = { fg = c.nontext },

    DiffAdd = { fg = c.foreground, bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { fg = c.foreground, bg = c.red_dark },
    DiffText = { fg = c.black, bg = c.green, bold = true },
    Added = { fg = c.green },
    Changed = { fg = c.orange },
    Removed = { fg = c.red },

    DiagnosticError = { fg = c.spell_bad },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.cyan },
    DiagnosticHint = { fg = c.green_bright },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.spell_bad, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.green_bright, undercurl = true },
    LspReferenceText = { bg = c.background_light },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.background_light, underline = true },
    LspSignatureActiveParameter = { fg = c.green_bright, bold = true },
    LspCodeLens = { fg = c.comment },

    SpellBad = { sp = c.spell_bad, undercurl = true },
    SpellCap = { sp = c.spell_cap, undercurl = true },
    SpellRare = { sp = c.spell_rare, undercurl = true },
    SpellLocal = { sp = c.spell_local, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.peach },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.yellow, bold = true },
    ["@variable"] = { fg = c.foreground },
    ["@variable.builtin"] = { fg = c.cyan, italic = true },
    ["@variable.parameter"] = { fg = c.orange },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.green_bright },
    ["@function.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.purple },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.blue },
    ["@keyword.return"] = { fg = c.magenta },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.purple, italic = true },
    ["@property"] = { fg = c.cyan },
    ["@attribute"] = { fg = c.yellow },
    ["@tag"] = { fg = c.green },
    ["@tag.attribute"] = { fg = c.cyan },
    ["@tag.delimiter"] = { fg = c.purple_dim },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.green_bright, underline = true },
    ["@markup.raw"] = { link = "String" },

    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.orange },
    GitSignsDelete = { fg = c.red },
    TelescopeBorder = { fg = c.purple },
    TelescopeSelection = { bg = c.background_alt, bold = true },
    TelescopeMatching = { fg = c.green_bright, bold = true },
    BlinkCmpLabelMatch = { fg = c.green_bright, bold = true },
    CmpItemAbbrMatch = { fg = c.green_bright, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.cyan, bold = true },
    lispList = { fg = c.nontext },
  }

  local links = {
    Repeat = "Statement", Label = "Statement", Include = "PreProc", Define = "PreProc",
    Macro = "PreProc", PreCondit = "PreProc", StorageClass = "Type", Structure = "Type",
    Typedef = "Type", Debug = "Special", SpecialChar = "Special", Tag = "Special",
    Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
