local M = {}

function M.setup(config)
  local c = require("gn.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.near_black
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.light_gray, bg = normal_bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.light_gray, bg = c.charcoal_black },
    FloatBorder = { fg = c.muted_gray, bg = c.charcoal_black },
    FloatTitle = { fg = c.pale_green, bg = c.charcoal_black, bold = true },
    Cursor = { fg = c.pure_black, bg = c.pale_green },
    NonText = { fg = c.deep_gray },
    EndOfBuffer = { fg = c.near_black },
    Whitespace = { fg = c.deep_gray },
    SpecialKey = { fg = c.dark_olive_yellow },
    LineNr = { fg = c.medium_gray, bg = normal_bg },
    CursorLineNr = { fg = c.pale_green, bg = normal_bg, bold = true },
    CursorLine = { bg = c.charcoal_black },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.charcoal_black },
    SignColumn = { fg = c.muted_cyan, bg = normal_bg },
    CursorLineSign = { bg = c.charcoal_black },
    FoldColumn = { fg = c.light_gray, bg = c.pure_black },
    Folded = { fg = c.dark_olive_yellow, bg = c.pure_black },
    MatchParen = { fg = c.pure_white, bg = c.deep_green, bold = true },
    Visual = { fg = c.muted_purple, bg = c.pure_white },
    VisualNOS = { fg = c.light_gray, bg = c.pure_black, underline = true },
    Search = { fg = c.light_gray, bg = c.dark_red },
    IncSearch = { fg = c.pure_black, bg = c.pale_green },
    CurSearch = { fg = c.pure_black, bg = c.pale_green, bold = true },
    Substitute = { fg = c.light_gray, bg = c.dark_red },
    Pmenu = { fg = c.light_gray, bg = c.charcoal_black },
    PmenuSel = { fg = c.light_violet, bg = c.pure_black, bold = true },
    PmenuKind = { fg = c.pale_green, bg = c.charcoal_black },
    PmenuExtra = { fg = c.medium_gray, bg = c.charcoal_black },
    PmenuSbar = { bg = c.pure_black },
    PmenuThumb = { bg = c.dark_gray },
    StatusLine = { fg = c.medium_gray, bg = normal_bg, bold = true },
    StatusLineNC = { fg = c.medium_gray, bg = normal_bg },
    TabLine = { fg = c.medium_gray, bg = c.dark_gray },
    TabLineFill = { bg = c.near_black },
    TabLineSel = { fg = c.light_gray, bg = c.charcoal_black, bold = true },
    WinSeparator = { fg = c.light_gray, bg = normal_bg },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.bright_violet, bg = c.pure_black, bold = true },
    Directory = { fg = c.pale_green },
    Title = { fg = c.muted_red, bold = true },
    Question = { fg = c.light_gray },
    MoreMsg = { fg = c.light_gray, bold = true },
    ModeMsg = { fg = c.light_gray, bold = true },
    WarningMsg = { fg = c.light_gray, bg = c.dark_red },
    ErrorMsg = { fg = c.light_gray, bg = c.dark_red },
    Error = { fg = c.deep_red, bg = c.pure_black },
    Todo = { fg = c.light_gray, bg = c.dark_red, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.muted_gray }, comment_style),
    SpecialComment = { fg = c.muted_gray, bold = true },
    Constant = { fg = c.olive_yellow },
    String = { fg = c.mint_green, bg = c.dark_forest_green },
    Character = { link = "String" },
    Number = { fg = c.light_brown },
    Boolean = { fg = c.pale_green, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.muted_cyan },
    Function = { fg = c.muted_cyan },
    Statement = vim.tbl_extend("force", { fg = c.bright_green }, keyword_style),
    Conditional = vim.tbl_extend("force", { fg = c.bright_magenta }, keyword_style),
    Keyword = vim.tbl_extend("force", { fg = c.cornflower_blue }, keyword_style),
    Operator = { fg = c.bright_green },
    Exception = { fg = c.bright_magenta },
    PreProc = { fg = c.muted_red },
    Type = { fg = c.light_violet },
    Special = { fg = c.pale_peach },
    Delimiter = { fg = c.lavender_gray },
    Underlined = { fg = c.light_gray, underline = true },
    Ignore = { fg = c.deep_gray },

    DiffAdd = { fg = c.light_gray, bg = c.dark_green },
    DiffChange = { bg = c.dark_purple },
    DiffDelete = { fg = c.light_gray, bg = c.dark_red },
    DiffText = { fg = c.pure_black, bg = c.bright_green, bold = true },
    Added = { fg = c.bright_green },
    Changed = { fg = c.light_brown },
    Removed = { fg = c.muted_red },

    DiagnosticError = { fg = c.soft_red },
    DiagnosticWarn = { fg = c.light_brown },
    DiagnosticInfo = { fg = c.muted_cyan },
    DiagnosticHint = { fg = c.pale_green },
    DiagnosticOk = { fg = c.bright_green },
    DiagnosticUnderlineError = { sp = c.soft_red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.light_brown, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.muted_cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.pale_green, undercurl = true },
    LspReferenceText = { bg = c.dark_gray },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.dark_gray, underline = true },
    LspSignatureActiveParameter = { fg = c.pale_green, bold = true },
    LspCodeLens = { fg = c.muted_gray },

    SpellBad = { sp = c.soft_red, undercurl = true },
    SpellCap = { sp = c.soft_cyan, undercurl = true },
    SpellRare = { sp = c.soft_magenta, undercurl = true },
    SpellLocal = { sp = c.soft_yellow, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.pale_peach },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.olive_yellow, bold = true },
    ["@variable"] = { fg = c.light_gray },
    ["@variable.builtin"] = { fg = c.muted_cyan, italic = true },
    ["@variable.parameter"] = { fg = c.light_brown },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.pale_green },
    ["@function.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.light_violet },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.cornflower_blue },
    ["@keyword.return"] = { fg = c.bright_magenta },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.light_violet, italic = true },
    ["@property"] = { fg = c.muted_cyan },
    ["@attribute"] = { fg = c.olive_yellow },
    ["@tag"] = { fg = c.bright_green },
    ["@tag.attribute"] = { fg = c.muted_cyan },
    ["@tag.delimiter"] = { fg = c.lavender_gray },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.pale_green, underline = true },
    ["@markup.raw"] = { link = "String" },

    GitSignsAdd = { fg = c.bright_green },
    GitSignsChange = { fg = c.light_brown },
    GitSignsDelete = { fg = c.muted_red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.charcoal_black, bold = true },
    TelescopeMatching = { fg = c.pale_green, bold = true },
    BlinkCmpLabelMatch = { fg = c.pale_green, bold = true },
    CmpItemAbbrMatch = { fg = c.pale_green, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.muted_cyan, bold = true },
    lispList = { fg = c.deep_gray },
  }

  local links = {
    Repeat = "Statement", Label = "Statement", Include = "PreProc", Define = "PreProc",
    Macro = "PreProc", PreCondit = "PreProc", StorageClass = "Type", Structure = "Type",
    Typedef = "Type", Debug = "Special", SpecialChar = "Special", Tag = "Special",
    Terminal = "Normal", QuickFixLine = "Search",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
