local M = {}

local function extend(base, style)
  return vim.tbl_extend("force", base, style or {})
end

function M.setup(config)
  local c = require("nd.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.nord0
  local sidebar_bg = config.contrast and c.nord1 or c.nord0
  local float_bg = config.contrast and c.nord1 or c.nord0
  local gutter_bg = normal_bg
  local border_fg = config.borders and c.nord3 or normal_bg
  local cursorline_bg = config.cursorline_transparent and none or c.nord1
  local sidebar_visible = not config.transparent or config.enable_sidebar_background
  local menu_bg = sidebar_visible and sidebar_bg or none
  local popup_bg = sidebar_visible and float_bg or none
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local diff = config.uniform_diff_background and {
    add = { fg = c.nord14, bg = c.nord1 },
    change = { fg = c.nord13, bg = c.nord1 },
    delete = { fg = c.nord11, bg = c.nord1 },
    text = { fg = c.nord8, bg = c.nord1, bold = true },
  } or {
    add = { bg = c.diff_add },
    change = { bg = c.diff_change },
    delete = { fg = c.nord11, bg = c.diff_delete },
    text = { bg = c.diff_text, bold = true },
  }

  local g = {
    Normal = { fg = c.nord4, bg = normal_bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.nord4, bg = popup_bg },
    FloatBorder = { fg = c.nord3, bg = popup_bg },
    FloatTitle = { fg = c.nord8, bg = popup_bg, bold = true },
    FloatFooter = { fg = c.nord3_bright, bg = popup_bg },
    Cursor = { fg = c.nord0, bg = c.nord4 },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    NonText = { fg = c.nord3 },
    EndOfBuffer = { fg = normal_bg },
    Whitespace = { fg = c.nord2 },
    SpecialKey = { fg = c.nord3_bright },
    Conceal = { fg = c.nord8, bold = true },
    LineNr = { fg = c.nord3_bright, bg = gutter_bg },
    CursorLineNr = { fg = c.nord8, bg = gutter_bg, bold = true },
    CursorLine = { bg = cursorline_bg },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { bg = c.nord1 },
    SignColumn = { fg = c.nord3, bg = gutter_bg },
    CursorLineSign = { bg = cursorline_bg },
    FoldColumn = { fg = c.nord3, bg = gutter_bg },
    Folded = { fg = c.nord3_bright, bg = c.nord1 },
    MatchParen = { fg = c.nord8, bg = c.nord2, bold = true },
    Visual = { bg = c.nord2 },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.nord0, bg = c.nord13 },
    IncSearch = { fg = c.nord0, bg = c.nord8 },
    CurSearch = { fg = c.nord0, bg = c.nord8, bold = true },
    Substitute = { fg = c.nord0, bg = c.nord11 },
    Pmenu = { fg = c.nord4, bg = menu_bg },
    PmenuSel = { fg = c.nord6, bg = c.nord2, bold = true },
    PmenuKind = { fg = c.nord8, bg = menu_bg },
    PmenuExtra = { fg = c.nord3_bright, bg = menu_bg },
    PmenuSbar = { bg = c.nord1 },
    PmenuThumb = { bg = c.nord3 },
    PmenuBorder = { link = "FloatBorder" },
    StatusLine = { fg = c.nord3_bright, bg = normal_bg },
    StatusLineNC = { fg = c.nord3_bright, bg = normal_bg },
    TabLine = { fg = c.nord3_bright, bg = c.nord1 },
    TabLineFill = { bg = normal_bg },
    TabLineSel = { fg = c.nord6, bg = c.nord2, bold = true },
    WinSeparator = { fg = c.nord6, bg = normal_bg, bold = true },
    VertSplit = { link = "WinSeparator" },
    WildMenu = { fg = c.nord0, bg = c.nord8, bold = true },
    Directory = { fg = c.nord8 },
    Title = { fg = c.nord8, bold = true },
    Question = { fg = c.nord14 },
    MoreMsg = { fg = c.nord14 },
    ModeMsg = { fg = c.nord13, bold = true },
    WarningMsg = { fg = c.nord13 },
    ErrorMsg = { fg = c.nord11 },
    Error = { fg = c.nord11 },
    Todo = { fg = c.nord0, bg = c.nord13, bold = true },

    Comment = extend({ fg = c.nord3_bright }, comment_style),
    SpecialComment = { fg = c.nord3_bright, bold = true },
    Constant = { fg = c.nord15 },
    String = { fg = c.nord14 },
    Character = { fg = c.nord14 },
    Number = { fg = c.nord15 },
    Boolean = { fg = c.nord9, bold = true },
    Float = { link = "Number" },
    Identifier = { fg = c.nord4 },
    Function = { fg = c.nord8 },
    Statement = extend({ fg = c.nord9 }, keyword_style),
    Conditional = extend({ fg = c.nord9 }, keyword_style),
    Keyword = extend({ fg = c.nord9 }, keyword_style),
    Operator = { fg = c.nord9 },
    Exception = { fg = c.nord9 },
    PreProc = { fg = c.nord10 },
    Type = { fg = c.nord7 },
    Special = { fg = c.nord8 },
    Delimiter = { fg = c.nord6 },
    Underlined = { fg = c.nord8, underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = c.nord3 },

    DiffAdd = diff.add,
    DiffChange = diff.change,
    DiffDelete = diff.delete,
    DiffText = diff.text,
    Added = { fg = c.nord14 },
    Changed = { fg = c.nord13 },
    Removed = { fg = c.nord11 },
    diffAdded = { fg = c.nord14 },
    diffChanged = { fg = c.nord13 },
    diffRemoved = { fg = c.nord11 },
    diffDeleted = { fg = c.nord11 },

    DiagnosticError = { fg = c.nord11 },
    DiagnosticWarn = { fg = c.nord13 },
    DiagnosticInfo = { fg = c.nord8 },
    DiagnosticHint = { fg = c.nord10 },
    DiagnosticOk = { fg = c.nord14 },
    DiagnosticFloatingError = { fg = c.nord11 },
    DiagnosticFloatingWarn = { fg = c.nord13 },
    DiagnosticFloatingInfo = { fg = c.nord8 },
    DiagnosticFloatingHint = { fg = c.nord10 },
    DiagnosticFloatingOk = { fg = c.nord14 },
    DiagnosticSignError = { fg = c.nord11, bg = gutter_bg },
    DiagnosticSignWarn = { fg = c.nord13, bg = gutter_bg },
    DiagnosticSignInfo = { fg = c.nord8, bg = gutter_bg },
    DiagnosticSignHint = { fg = c.nord10, bg = gutter_bg },
    DiagnosticSignOk = { fg = c.nord14, bg = gutter_bg },
    DiagnosticVirtualTextError = { fg = c.nord11, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.nord13, bg = c.diff_change },
    DiagnosticVirtualTextInfo = { fg = c.nord8, bg = c.diff_change },
    DiagnosticVirtualTextHint = { fg = c.nord10, bg = c.diff_change },
    DiagnosticUnderlineError = { sp = c.nord11, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.nord13, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.nord8, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.nord10, undercurl = true },
    LspReferenceText = { bg = c.nord2 },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.nord2, underline = true },
    LspSignatureActiveParameter = { fg = c.nord8, bold = true },
    LspCodeLens = { fg = c.nord3_bright },

    SpellBad = { sp = c.nord11, undercurl = true },
    SpellCap = { sp = c.nord13, undercurl = true },
    SpellRare = { sp = c.nord15, undercurl = true },
    SpellLocal = { sp = c.nord8, undercurl = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.nord13 },
    ["@string.regexp"] = { fg = c.nord13 },
    ["@string.special"] = { fg = c.nord8 },
    ["@string.special.url"] = { fg = c.nord8, underline = true },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.nord9, bold = true },
    ["@variable"] = { fg = c.nord4 },
    ["@variable.builtin"] = { fg = c.nord9, italic = true },
    ["@variable.parameter"] = { fg = c.nord15 },
    ["@variable.member"] = { fg = c.nord7 },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.nord8 },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@constructor"] = { fg = c.nord7 },
    ["@module"] = { fg = c.nord7 },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = extend({ fg = c.nord9 }, keyword_style),
    ["@keyword.return"] = extend({ fg = c.nord9 }, keyword_style),
    ["@keyword.operator"] = { fg = c.nord9 },
    ["@keyword.import"] = { link = "PreProc" },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.nord7, italic = true },
    ["@property"] = { fg = c.nord7 },
    ["@attribute"] = { fg = c.nord10 },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = c.nord6 },
    ["@punctuation.special"] = { fg = c.nord8 },
    ["@tag"] = { fg = c.nord9 },
    ["@tag.attribute"] = { fg = c.nord7 },
    ["@tag.delimiter"] = { fg = c.nord6 },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.link"] = { fg = c.nord8, underline = true },
    ["@markup.link.url"] = { fg = c.nord8, underline = true },
    ["@markup.raw"] = { link = "String" },
    ["@diff.plus"] = { fg = c.nord14 },
    ["@diff.minus"] = { fg = c.nord11 },
    ["@diff.delta"] = { fg = c.nord13 },

    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.keyword"] = { link = "Keyword" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.readonly"] = { link = "Constant" },
    ["@lsp.mod.defaultLibrary"] = { link = "Special" },

    GitSignsAdd = { fg = c.nord14, bg = gutter_bg },
    GitSignsChange = { fg = c.nord13, bg = gutter_bg },
    GitSignsDelete = { fg = c.nord11, bg = gutter_bg },
    GitGutterAdd = { link = "GitSignsAdd" },
    GitGutterChange = { link = "GitSignsChange" },
    GitGutterDelete = { link = "GitSignsDelete" },
    TelescopeBorder = { fg = c.nord6, bg = popup_bg },
    TelescopePromptBorder = { fg = c.nord6, bg = popup_bg },
    TelescopeResultsBorder = { fg = c.nord6, bg = popup_bg },
    TelescopePreviewBorder = { fg = c.nord6, bg = popup_bg },
    TelescopeSelection = { bg = c.nord1, bold = true },
    TelescopeSelectionCaret = { fg = c.nord8, bg = c.nord1 },
    TelescopeMatching = { fg = c.nord8, bold = true },
    TelescopeTitle = { fg = c.nord8, bold = true },
    NvimTreeNormal = { fg = c.nord4, bg = sidebar_visible and sidebar_bg or none },
    NvimTreeNormalNC = { link = "NvimTreeNormal" },
    NvimTreeFolderName = { fg = c.nord8 },
    NvimTreeOpenedFolderName = { fg = c.nord8, bold = true },
    NvimTreeRootFolder = { fg = c.nord8, bold = true },
    NvimTreeGitDirty = { fg = c.nord13 },
    NvimTreeGitNew = { fg = c.nord14 },
    NvimTreeGitDeleted = { fg = c.nord11 },
    WhichKey = { fg = c.nord8 },
    WhichKeyGroup = { fg = c.nord7 },
    WhichKeyDesc = { fg = c.nord4 },
    WhichKeySeparator = { fg = c.nord3 },
    WhichKeyFloat = { bg = popup_bg },
    IndentBlanklineChar = { fg = c.nord2 },
    IblIndent = { fg = c.nord2 },
    IblScope = { fg = c.nord3_bright },
    TreesitterContext = { bg = c.nord1 },
    TreesitterContextLineNumber = { fg = c.nord8, bg = c.nord1 },

    CmpDocumentation = { link = "NormalFloat" },
    CmpDocumentationBorder = { link = "FloatBorder" },
    CmpItemAbbr = { fg = c.nord4 },
    CmpItemAbbrDeprecated = { fg = c.nord3_bright, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.nord8, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.nord7, bold = true },
    CmpItemKind = { fg = c.nord7 },
    CmpItemMenu = { fg = c.nord3_bright },
    CmpGhostText = { fg = c.nord3 },
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpLabel = { fg = c.nord4 },
    BlinkCmpLabelMatch = { fg = c.nord8, bold = true },
    BlinkCmpLabelDetails = { fg = c.nord3_bright },
    BlinkCmpLabelDeprecated = { fg = c.nord3_bright, strikethrough = true },
    BlinkCmpGhostText = { fg = c.nord3 },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpKind = { fg = c.nord7 },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
  }

  local links = {
    Repeat = "Statement",
    Label = "Statement",
    Include = "PreProc",
    Define = "PreProc",
    Macro = "PreProc",
    PreCondit = "PreProc",
    StorageClass = "Type",
    Structure = "Type",
    Typedef = "Type",
    Debug = "Special",
    SpecialChar = "Special",
    Tag = "Special",
    Terminal = "Normal",
    QuickFixLine = "Search",
    WinBar = "StatusLine",
    WinBarNC = "StatusLineNC",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
