local M = {}

function M.setup(config)
  local c = require("st.palette")
  local none = "NONE"
  local normal_bg = config.transparent and none or c.dark_gray
  local comment_style = config.styles.comments or {}
  local keyword_style = config.styles.keywords or {}

  local g = {
    Normal = { fg = c.silver, bg = normal_bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = c.silver, bg = c.dark_slate },
    FloatBorder = { fg = c.slate, bg = c.dark_slate },
    FloatTitle = { fg = c.gold, bg = c.dark_slate, bold = true },
    NonText = { fg = c.cool_gray, bg = normal_bg },
    EndOfBuffer = { fg = c.slate, bg = normal_bg },
    Whitespace = { fg = c.slate },
    LineNr = { fg = c.charcoal, bg = c.dark_gray },
    CursorLineNr = { fg = c.gold, bg = c.dark_gray, bold = true },
    CursorLine = { bg = c.dark_slate },
    CursorColumn = { bg = c.dark_slate },
    ColorColumn = { bg = c.dark_slate },
    SignColumn = { fg = c.slate, bg = c.dark_gray },
    CursorLineSign = { bg = c.dark_gray },
    FoldColumn = { fg = c.slate, bg = c.black },
    Folded = { fg = c.gray, bg = c.charcoal },
    MatchParen = { fg = c.sand, bold = true },
    Visual = { bg = c.graphite },
    VisualNOS = { fg = c.silver, bg = c.dark_gray },
    Search = { fg = c.dark_gray, bg = c.sand, bold = true },
    IncSearch = { fg = c.dark_gray, bg = c.light_yellow, bold = true },
    CurSearch = { link = "IncSearch" },
    Substitute = { link = "Search" },
    Pmenu = { fg = c.silver, bg = c.dark_slate },
    PmenuSel = { fg = c.dark_gray, bg = c.gold, bold = true },
    PmenuSbar = { bg = c.dark_slate },
    PmenuThumb = { bg = c.light_green },
    StatusLine = { fg = c.charcoal, bg = c.dark_gray },
    StatusLineNC = { fg = c.charcoal, bg = c.dark_gray },
    TabLine = { fg = c.silver, bg = c.black },
    TabLineFill = { fg = c.silver, bg = c.black },
    TabLineSel = { fg = c.silver, bg = c.dark_gray, bold = true },
    WinSeparator = { fg = c.cool_gray },
    VertSplit = { link = "WinSeparator" },
    Directory = { fg = c.gold },
    Title = { fg = c.gold, bold = true },
    Question = { fg = c.silver },
    MoreMsg = { fg = c.light_green },
    ModeMsg = { fg = c.sand },
    WarningMsg = { fg = c.gold },
    ErrorMsg = { fg = c.muted_red },
    Error = { fg = c.muted_red },
    Todo = { fg = c.light_green, bold = true },

    Comment = vim.tbl_extend("force", { fg = c.cool_gray }, comment_style),
    SpecialComment = { fg = c.steel_gray },
    Constant = { fg = c.near_white },
    String = { fg = c.light_cyan },
    Identifier = { fg = c.light_green },
    Function = { fg = c.light_green },
    Statement = vim.tbl_extend("force", { fg = c.gold, bold = true }, keyword_style),
    PreProc = { fg = c.lavender },
    Type = { fg = c.near_white },
    Special = { fg = c.sand, bold = true },
    Operator = { fg = c.light_green },
    Delimiter = { fg = c.silver },
    Underlined = { fg = c.light_green, underline = true },

    DiffAdd = { fg = c.light_cyan },
    DiffChange = { fg = c.gold },
    DiffDelete = { fg = c.muted_red },
    DiffText = { fg = c.light_green, bold = true },
    Added = { link = "DiffAdd" },
    Changed = { link = "DiffChange" },
    Removed = { link = "DiffDelete" },

    DiagnosticError = { fg = c.muted_red },
    DiagnosticWarn = { fg = c.gold },
    DiagnosticInfo = { fg = c.light_cyan },
    DiagnosticHint = { fg = c.light_green },
    DiagnosticOk = { fg = c.light_green },
    DiagnosticUnderlineError = { sp = c.muted_red, underline = true },
    DiagnosticUnderlineWarn = { sp = c.gold, underline = true },
    DiagnosticUnderlineInfo = { sp = c.light_cyan, underline = true },
    DiagnosticUnderlineHint = { sp = c.light_green, underline = true },
    LspReferenceText = { bg = c.graphite },
    LspReferenceRead = { bg = c.graphite },
    LspReferenceWrite = { bg = c.graphite, bold = true },
    LspSignatureActiveParameter = { fg = c.gold, bold = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "SpecialComment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.sand },
    ["@variable"] = { fg = c.silver },
    ["@variable.builtin"] = { fg = c.sand },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.light_green },
    ["@function.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.near_white },
    ["@keyword"] = { link = "Statement" },
    ["@keyword.function"] = { link = "Statement" },
    ["@keyword.return"] = { link = "Statement" },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.near_white },
    ["@property"] = { fg = c.silver },
    ["@attribute"] = { fg = c.lavender },
    ["@tag"] = { fg = c.gold, bold = true },
    ["@tag.attribute"] = { fg = c.light_green },
    ["@tag.delimiter"] = { fg = c.silver },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.link"] = { fg = c.sand, underline = true },
    ["@markup.raw"] = { link = "String" },

    GitSignsAdd = { fg = c.light_cyan },
    GitSignsChange = { fg = c.gold },
    GitSignsDelete = { fg = c.muted_red },
    TelescopeBorder = { fg = "#FFFFFF" },
    TelescopeSelection = { bg = c.graphite, bold = true },
    TelescopeMatching = { fg = c.gold, bold = true },
    BlinkCmpLabelMatch = { fg = c.gold, bold = true },
    CmpItemAbbrMatch = { fg = c.gold, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.sand, bold = true },
  }

  local links = {
    Boolean = "Constant", Character = "Constant", Number = "Constant", Float = "Number",
    Conditional = "Statement", Repeat = "Statement", Label = "Statement", Keyword = "Statement",
    Exception = "Statement", Include = "PreProc", Define = "PreProc", Macro = "PreProc",
    PreCondit = "PreProc", StorageClass = "Statement", Structure = "Statement", Typedef = "Statement",
    Debug = "Special", SpecialChar = "Special", Tag = "Special", Terminal = "Normal",
    QuickFixLine = "Search", SpellBad = "DiagnosticUnderlineError", SpellCap = "DiagnosticUnderlineWarn",
    SpellLocal = "DiagnosticUnderlineInfo", SpellRare = "DiagnosticUnderlineHint",
  }

  for name, target in pairs(links) do
    g[name] = { link = target }
  end

  return g
end

return M
